//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 11:46:26 AM WAT 
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{}MessageHeaderType"/>
 *         &lt;choice>
 *           &lt;element name="IndividualReport" type="{}IndividualReportType"/>
 *         &lt;/choice>
 *         &lt;element name="Validation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "messageHeader", "individualReport", "validation" })
@XmlRootElement(name = "Container")
@JsonIgnoreProperties(ignoreUnknown = true)
//@JsonInclude(JsonInclude.Include.NON_NULL)
public class Container {
	
	@XmlElement(name = "MessageHeader", required = true)
	protected MessageHeaderType messageHeader;
	
	@XmlElement(name = "IndividualReport")
	protected IndividualReportType individualReport;
	
	@XmlElement(name = "Validation")
	protected String validation;
	
	/**
	 * Gets the value of the messageHeader property.
	 * 
	 * @return possible object is {@link MessageHeaderType }
	 */
	public MessageHeaderType getMessageHeader() {
		return messageHeader;
	}
	
	/**
	 * Sets the value of the messageHeader property.
	 * 
	 * @param value allowed object is {@link MessageHeaderType }
	 */
	public void setMessageHeader(MessageHeaderType value) {
		this.messageHeader = value;
	}
	
	/**
	 * Gets the value of the individualReport property.
	 * 
	 * @return possible object is {@link IndividualReportType }
	 */
	public IndividualReportType getIndividualReport() {
		return individualReport;
	}
	
	/**
	 * Sets the value of the individualReport property.
	 * 
	 * @param value allowed object is {@link IndividualReportType }
	 */
	public void setIndividualReport(IndividualReportType value) {
		this.individualReport = value;
	}
	
	/**
	 * Gets the value of the validation property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getValidation() {
		return validation;
	}
	
	/**
	 * Sets the value of the validation property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setValidation(String value) {
		this.validation = value;
	}
	
}
