//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.01 at 09:42:41 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DRTBTreatmentRegisterType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DRTBTreatmentRegisterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{}StringType"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PatientSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateRegistered" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PlaceOfInitiation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LGADRTBRegNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferringHealthFacility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferringFacilityState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferringFacilityLGA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreviouslyOnTB2ndLineDrug" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="Weight" type="{}NumericType" minOccurs="0"/>
 *         &lt;element name="Height" type="{}NumericType" minOccurs="0"/>
 *         &lt;element name="TypeOfTreatmentRegimen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="ShorterRegimen_Injectable"/>
 *               &lt;enumeration value="ShorterRegimen_BDQ"/>
 *               &lt;enumeration value="Individualized_PREXDR"/>
 *               &lt;enumeration value="Individualized_XDR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EnterBDQOrDim" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateTreatmentStarted" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="SiteOfDisease" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Pulmonary"/>
 *               &lt;enumeration value="ExtraPulmonary"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RegistrationGroup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="New"/>
 *               &lt;enumeration value="Relapse"/>
 *               &lt;enumeration value="TreatmentAfterFailure"/>
 *               &lt;enumeration value="TreatmentAfterLossToFollowUp"/>
 *               &lt;enumeration value="OthersPreviouslyTreated"/>
 *               &lt;enumeration value="TBPatient"/>
 *               &lt;enumeration value="UnknownPreviousTB"/>
 *               &lt;enumeration value="TransferredIn"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GeneXpert" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Resistant"/>
 *               &lt;enumeration value="Susceptible"/>
 *               &lt;enumeration value="NotDone"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AFB" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="PositiveSmear"/>
 *               &lt;enumeration value="NegativeSmear"/>
 *               &lt;enumeration value="NotDone"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Culture" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="PositiveCulture"/>
 *               &lt;enumeration value="NegativeCulture"/>
 *               &lt;enumeration value="Contaminated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LPAResult" type="{}LPAResultType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DSTResult" type="{}DSTResultType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XRayDone" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="FollowUpInvestigation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Month" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}CodeType">
 *                         &lt;enumeration value="Month1"/>
 *                         &lt;enumeration value="Month2"/>
 *                         &lt;enumeration value="Month3"/>
 *                         &lt;enumeration value="Month4"/>
 *                         &lt;enumeration value="Month5"/>
 *                         &lt;enumeration value="Month6"/>
 *                         &lt;enumeration value="Month7"/>
 *                         &lt;enumeration value="Month8"/>
 *                         &lt;enumeration value="Month9"/>
 *                         &lt;enumeration value="Month10"/>
 *                         &lt;enumeration value="Month11"/>
 *                         &lt;enumeration value="Month12"/>
 *                         &lt;enumeration value="Month13"/>
 *                         &lt;enumeration value="Month14"/>
 *                         &lt;enumeration value="Month15"/>
 *                         &lt;enumeration value="Month16"/>
 *                         &lt;enumeration value="Month17"/>
 *                         &lt;enumeration value="Month18"/>
 *                         &lt;enumeration value="Month19"/>
 *                         &lt;enumeration value="Month20"/>
 *                         &lt;enumeration value="Month21"/>
 *                         &lt;enumeration value="Month22"/>
 *                         &lt;enumeration value="Month23"/>
 *                         &lt;enumeration value="Month24"/>
 *                         &lt;enumeration value="Month25"/>
 *                         &lt;enumeration value="Month26"/>
 *                         &lt;enumeration value="Month27"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SmearResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CultureResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ResultDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HIVStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Positive"/>
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Unknown"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CPT" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="ARTStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CPTStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Outcome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="CompletedTreatmentForDisease"/>
 *               &lt;enumeration value="Cure_Outcome"/>
 *               &lt;enumeration value="Die"/>
 *               &lt;enumeration value="LostToFollowup"/>
 *               &lt;enumeration value="NotAssessed"/>
 *               &lt;enumeration value="PatientMovedToMultiDrugResistantTBRegister"/>
 *               &lt;enumeration value="TBTreatmentFailure"/>
 *               &lt;enumeration value="TBTreatmentFailureAndSmearPositiveAt3Months"/>
 *               &lt;enumeration value="TBTreatmentFailureAndSmearPositiveAt5Months"/>
 *               &lt;enumeration value="TBTreatmentFailureAndSmearPositiveAt8Months"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OutcomeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRTBTreatmentRegisterType", propOrder = { "visitID", "visitDate", "patientSerialNumber", "dateRegistered",
        "placeOfInitiation", "lgadrtbRegNo", "referringHealthFacility", "referringFacilityState", "referringFacilityLGA",
        "previouslyOnTB2NdLineDrug", "weight", "height", "typeOfTreatmentRegimen", "enterBDQOrDim", "dateTreatmentStarted",
        "siteOfDisease", "registrationGroup", "geneXpert", "afb", "culture", "lpaResult", "dstResult", "xRayDone",
        "xRayResult", "followUpInvestigation", "hivStatus", "cpt", "artStartDate", "cptStartDate", "outcome", "outcomeDate",
        "comment" })
public class DRTBTreatmentRegisterType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "PatientSerialNumber")
	protected String patientSerialNumber;
	
	@XmlElement(name = "DateRegistered")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateRegistered;
	
	@XmlElement(name = "PlaceOfInitiation")
	protected String placeOfInitiation;
	
	@XmlElement(name = "LGADRTBRegNo")
	protected String lgadrtbRegNo;
	
	@XmlElement(name = "ReferringHealthFacility")
	protected String referringHealthFacility;
	
	@XmlElement(name = "ReferringFacilityState")
	protected String referringFacilityState;
	
	@XmlElement(name = "ReferringFacilityLGA")
	protected String referringFacilityLGA;
	
	@XmlElement(name = "PreviouslyOnTB2ndLineDrug")
	@XmlSchemaType(name = "string")
	protected YNCodeType previouslyOnTB2NdLineDrug;
	
	@XmlElement(name = "Weight")
	protected Float weight;
	
	@XmlElement(name = "Height")
	protected Float height;
	
	@XmlElement(name = "TypeOfTreatmentRegimen")
	protected String typeOfTreatmentRegimen;
	
	@XmlElement(name = "EnterBDQOrDim")
	protected String enterBDQOrDim;
	
	@XmlElement(name = "DateTreatmentStarted")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateTreatmentStarted;
	
	@XmlElement(name = "SiteOfDisease")
	protected String siteOfDisease;
	
	@XmlElement(name = "RegistrationGroup")
	protected String registrationGroup;
	
	@XmlElement(name = "GeneXpert")
	protected String geneXpert;
	
	@XmlElement(name = "AFB")
	protected String afb;
	
	@XmlElement(name = "Culture")
	protected String culture;
	
	@XmlElement(name = "LPAResult")
	protected List<LPAResultType> lpaResult;
	
	@XmlElement(name = "DSTResult")
	protected List<DSTResultType> dstResult;
	
	@XmlElement(name = "XRayDone")
	@XmlSchemaType(name = "string")
	protected YNCodeType xRayDone;
	
	@XmlElement(name = "XRayResult")
	protected String xRayResult;
	
	@XmlElement(name = "FollowUpInvestigation")
	protected List<DRTBTreatmentRegisterType.FollowUpInvestigation> followUpInvestigation;
	
	@XmlElement(name = "HIVStatus")
	protected String hivStatus;
	
	@XmlElement(name = "CPT")
	@XmlSchemaType(name = "string")
	protected YNCodeType cpt;
	
	@XmlElement(name = "ARTStartDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar artStartDate;
	
	@XmlElement(name = "CPTStartDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar cptStartDate;
	
	@XmlElement(name = "Outcome")
	protected String outcome;
	
	@XmlElement(name = "OutcomeDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar outcomeDate;
	
	@XmlElement(name = "Comment")
	protected String comment;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the patientSerialNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPatientSerialNumber() {
		return patientSerialNumber;
	}
	
	/**
	 * Sets the value of the patientSerialNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPatientSerialNumber(String value) {
		this.patientSerialNumber = value;
	}
	
	/**
	 * Gets the value of the dateRegistered property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateRegistered() {
		return dateRegistered;
	}
	
	/**
	 * Sets the value of the dateRegistered property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateRegistered(XMLGregorianCalendar value) {
		this.dateRegistered = value;
	}
	
	/**
	 * Gets the value of the placeOfInitiation property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPlaceOfInitiation() {
		return placeOfInitiation;
	}
	
	/**
	 * Sets the value of the placeOfInitiation property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPlaceOfInitiation(String value) {
		this.placeOfInitiation = value;
	}
	
	/**
	 * Gets the value of the lgadrtbRegNo property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLGADRTBRegNo() {
		return lgadrtbRegNo;
	}
	
	/**
	 * Sets the value of the lgadrtbRegNo property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLGADRTBRegNo(String value) {
		this.lgadrtbRegNo = value;
	}
	
	/**
	 * Gets the value of the referringHealthFacility property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReferringHealthFacility() {
		return referringHealthFacility;
	}
	
	/**
	 * Sets the value of the referringHealthFacility property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReferringHealthFacility(String value) {
		this.referringHealthFacility = value;
	}
	
	/**
	 * Gets the value of the referringFacilityState property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReferringFacilityState() {
		return referringFacilityState;
	}
	
	/**
	 * Sets the value of the referringFacilityState property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReferringFacilityState(String value) {
		this.referringFacilityState = value;
	}
	
	/**
	 * Gets the value of the referringFacilityLGA property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReferringFacilityLGA() {
		return referringFacilityLGA;
	}
	
	/**
	 * Sets the value of the referringFacilityLGA property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReferringFacilityLGA(String value) {
		this.referringFacilityLGA = value;
	}
	
	/**
	 * Gets the value of the previouslyOnTB2NdLineDrug property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getPreviouslyOnTB2NdLineDrug() {
		return previouslyOnTB2NdLineDrug;
	}
	
	/**
	 * Sets the value of the previouslyOnTB2NdLineDrug property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setPreviouslyOnTB2NdLineDrug(YNCodeType value) {
		this.previouslyOnTB2NdLineDrug = value;
	}
	
	/**
	 * Gets the value of the weight property.
	 * 
	 * @return possible object is {@link Float }
	 */
	public Float getWeight() {
		return weight;
	}
	
	/**
	 * Sets the value of the weight property.
	 * 
	 * @param value allowed object is {@link Float }
	 */
	public void setWeight(Float value) {
		this.weight = value;
	}
	
	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link Float }
	 */
	public Float getHeight() {
		return height;
	}
	
	/**
	 * Sets the value of the height property.
	 * 
	 * @param value allowed object is {@link Float }
	 */
	public void setHeight(Float value) {
		this.height = value;
	}
	
	/**
	 * Gets the value of the typeOfTreatmentRegimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTypeOfTreatmentRegimen() {
		return typeOfTreatmentRegimen;
	}
	
	/**
	 * Sets the value of the typeOfTreatmentRegimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTypeOfTreatmentRegimen(String value) {
		this.typeOfTreatmentRegimen = value;
	}
	
	/**
	 * Gets the value of the enterBDQOrDim property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getEnterBDQOrDim() {
		return enterBDQOrDim;
	}
	
	/**
	 * Sets the value of the enterBDQOrDim property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setEnterBDQOrDim(String value) {
		this.enterBDQOrDim = value;
	}
	
	/**
	 * Gets the value of the dateTreatmentStarted property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateTreatmentStarted() {
		return dateTreatmentStarted;
	}
	
	/**
	 * Sets the value of the dateTreatmentStarted property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateTreatmentStarted(XMLGregorianCalendar value) {
		this.dateTreatmentStarted = value;
	}
	
	/**
	 * Gets the value of the siteOfDisease property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSiteOfDisease() {
		return siteOfDisease;
	}
	
	/**
	 * Sets the value of the siteOfDisease property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSiteOfDisease(String value) {
		this.siteOfDisease = value;
	}
	
	/**
	 * Gets the value of the registrationGroup property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRegistrationGroup() {
		return registrationGroup;
	}
	
	/**
	 * Sets the value of the registrationGroup property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRegistrationGroup(String value) {
		this.registrationGroup = value;
	}
	
	/**
	 * Gets the value of the geneXpert property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getGeneXpert() {
		return geneXpert;
	}
	
	/**
	 * Sets the value of the geneXpert property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setGeneXpert(String value) {
		this.geneXpert = value;
	}
	
	/**
	 * Gets the value of the afb property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAFB() {
		return afb;
	}
	
	/**
	 * Sets the value of the afb property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAFB(String value) {
		this.afb = value;
	}
	
	/**
	 * Gets the value of the culture property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCulture() {
		return culture;
	}
	
	/**
	 * Sets the value of the culture property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setCulture(String value) {
		this.culture = value;
	}
	
	/**
	 * Gets the value of the lpaResult property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the lpaResult property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
     *    getLPAResult().add(newItem);
     * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link LPAResultType }
	 */
	public List<LPAResultType> getLPAResult() {
		if (lpaResult == null) {
			lpaResult = new ArrayList<LPAResultType>();
		}
		return this.lpaResult;
	}
	
	public void setLPAResult(List<LPAResultType> lpaResult) {
		this.lpaResult = lpaResult;
	}
	
	/**
	 * Gets the value of the dstResult property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the dstResult property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
     *    getDSTResult().add(newItem);
     * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link DSTResultType }
	 */
	public List<DSTResultType> getDSTResult() {
		if (dstResult == null) {
			dstResult = new ArrayList<DSTResultType>();
		}
		return this.dstResult;
	}
	
	public void setDSTResult(List<DSTResultType> dstResult) {
		this.dstResult = dstResult;
	}
	
	/**
	 * Gets the value of the xRayDone property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getXRayDone() {
		return xRayDone;
	}
	
	/**
	 * Sets the value of the xRayDone property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setXRayDone(YNCodeType value) {
		this.xRayDone = value;
	}
	
	/**
	 * Gets the value of the xRayResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getXRayResult() {
		return xRayResult;
	}
	
	/**
	 * Sets the value of the xRayResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setXRayResult(String value) {
		this.xRayResult = value;
	}
	
	/**
	 * Gets the value of the followUpInvestigation property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the followUpInvestigation property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
     *    getFollowUpInvestigation().add(newItem);
     * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DRTBTreatmentRegisterType.FollowUpInvestigation }
	 */
	public List<DRTBTreatmentRegisterType.FollowUpInvestigation> getFollowUpInvestigation() {
		if (followUpInvestigation == null) {
			followUpInvestigation = new ArrayList<DRTBTreatmentRegisterType.FollowUpInvestigation>();
		}
		return this.followUpInvestigation;
	}
	
	public void setFollowUpInvestigation(List<DRTBTreatmentRegisterType.FollowUpInvestigation> followUpInvestigation) {
		this.followUpInvestigation = followUpInvestigation;
	}
	
	/**
	 * Gets the value of the hivStatus property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getHIVStatus() {
		return hivStatus;
	}
	
	/**
	 * Sets the value of the hivStatus property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setHIVStatus(String value) {
		this.hivStatus = value;
	}
	
	/**
	 * Gets the value of the cpt property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getCPT() {
		return cpt;
	}
	
	/**
	 * Sets the value of the cpt property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setCPT(YNCodeType value) {
		this.cpt = value;
	}
	
	/**
	 * Gets the value of the artStartDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getARTStartDate() {
		return artStartDate;
	}
	
	/**
	 * Sets the value of the artStartDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setARTStartDate(XMLGregorianCalendar value) {
		this.artStartDate = value;
	}
	
	/**
	 * Gets the value of the cptStartDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getCPTStartDate() {
		return cptStartDate;
	}
	
	/**
	 * Sets the value of the cptStartDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setCPTStartDate(XMLGregorianCalendar value) {
		this.cptStartDate = value;
	}
	
	/**
	 * Gets the value of the outcome property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOutcome() {
		return outcome;
	}
	
	/**
	 * Sets the value of the outcome property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOutcome(String value) {
		this.outcome = value;
	}
	
	/**
	 * Gets the value of the outcomeDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getOutcomeDate() {
		return outcomeDate;
	}
	
	/**
	 * Sets the value of the outcomeDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setOutcomeDate(XMLGregorianCalendar value) {
		this.outcomeDate = value;
	}
	
	/**
	 * Gets the value of the comment property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getComment() {
		return comment;
	}
	
	/**
	 * Sets the value of the comment property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setComment(String value) {
		this.comment = value;
	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Month" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{}CodeType">
     *               &lt;enumeration value="Month1"/>
     *               &lt;enumeration value="Month2"/>
     *               &lt;enumeration value="Month3"/>
     *               &lt;enumeration value="Month4"/>
     *               &lt;enumeration value="Month5"/>
     *               &lt;enumeration value="Month6"/>
     *               &lt;enumeration value="Month7"/>
     *               &lt;enumeration value="Month8"/>
     *               &lt;enumeration value="Month9"/>
     *               &lt;enumeration value="Month10"/>
     *               &lt;enumeration value="Month11"/>
     *               &lt;enumeration value="Month12"/>
     *               &lt;enumeration value="Month13"/>
     *               &lt;enumeration value="Month14"/>
     *               &lt;enumeration value="Month15"/>
     *               &lt;enumeration value="Month16"/>
     *               &lt;enumeration value="Month17"/>
     *               &lt;enumeration value="Month18"/>
     *               &lt;enumeration value="Month19"/>
     *               &lt;enumeration value="Month20"/>
     *               &lt;enumeration value="Month21"/>
     *               &lt;enumeration value="Month22"/>
     *               &lt;enumeration value="Month23"/>
     *               &lt;enumeration value="Month24"/>
     *               &lt;enumeration value="Month25"/>
     *               &lt;enumeration value="Month26"/>
     *               &lt;enumeration value="Month27"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SmearResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CultureResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ResultDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "month", "smearResult", "cultureResult", "resultDate" })
	public static class FollowUpInvestigation {
		
		@XmlElement(name = "Month")
		protected String month;
		
		@XmlElement(name = "SmearResult")
		protected String smearResult;
		
		@XmlElement(name = "CultureResult")
		protected String cultureResult;
		
		@XmlElement(name = "ResultDate")
		@XmlSchemaType(name = "date")
		protected XMLGregorianCalendar resultDate;
		
		/**
		 * Gets the value of the month property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getMonth() {
			return month;
		}
		
		/**
		 * Sets the value of the month property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setMonth(String value) {
			this.month = value;
		}
		
		/**
		 * Gets the value of the smearResult property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getSmearResult() {
			return smearResult;
		}
		
		/**
		 * Sets the value of the smearResult property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setSmearResult(String value) {
			this.smearResult = value;
		}
		
		/**
		 * Gets the value of the cultureResult property.
		 * 
		 * @return possible object is {@link String }
		 */
		public String getCultureResult() {
			return cultureResult;
		}
		
		/**
		 * Sets the value of the cultureResult property.
		 * 
		 * @param value allowed object is {@link String }
		 */
		public void setCultureResult(String value) {
			this.cultureResult = value;
		}
		
		/**
		 * Gets the value of the resultDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 */
		public XMLGregorianCalendar getResultDate() {
			return resultDate;
		}
		
		/**
		 * Sets the value of the resultDate property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 */
		public void setResultDate(XMLGregorianCalendar value) {
			this.resultDate = value;
		}
		
	}
	
}
