//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.01 at 09:42:41 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DSTResultType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DSTResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NameDSTResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameDSTResultResistantPattern" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Resistant"/>
 *               &lt;enumeration value="Susceptible"/>
 *               &lt;enumeration value="Contaminated"/>
 *               &lt;enumeration value="NotDone"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DSTResultType", propOrder = { "nameDSTResult", "nameDSTResultResistantPattern" })
public class DSTResultType {
	
	@XmlElement(name = "NameDSTResult")
	protected String nameDSTResult;
	
	@XmlElement(name = "NameDSTResultResistantPattern")
	protected String nameDSTResultResistantPattern;
	
	/**
	 * Gets the value of the nameDSTResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameDSTResult() {
		return nameDSTResult;
	}
	
	/**
	 * Sets the value of the nameDSTResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameDSTResult(String value) {
		this.nameDSTResult = value;
	}
	
	/**
	 * Gets the value of the nameDSTResultResistantPattern property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameDSTResultResistantPattern() {
		return nameDSTResultResistantPattern;
	}
	
	/**
	 * Sets the value of the nameDSTResultResistantPattern property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameDSTResultResistantPattern(String value) {
		this.nameDSTResultResistantPattern = value;
	}
	
}
