//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 11:46:26 AM WAT 
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for FingerPrintType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerPrintType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateCaptured" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="rightHand" type="{}rightHandType"/>
 *         &lt;element name="leftHand" type="{}leftHandType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FingerPrintType", propOrder = { "dateCaptured", "rightHand", "leftHand" })
public class FingerPrintType {
	
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateCaptured;
	
	@XmlElement(required = true)
	protected RightHandType rightHand;
	
	@XmlElement(required = true)
	protected LeftHandType leftHand;
	
	/**
	 * Gets the value of the dateCaptured property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateCaptured() {
		return dateCaptured;
	}
	
	/**
	 * Sets the value of the dateCaptured property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateCaptured(XMLGregorianCalendar value) {
		this.dateCaptured = value;
	}
	
	/**
	 * Gets the value of the rightHand property.
	 * 
	 * @return possible object is {@link RightHandType }
	 */
	public RightHandType getRightHand() {
		return rightHand;
	}
	
	/**
	 * Sets the value of the rightHand property.
	 * 
	 * @param value allowed object is {@link RightHandType }
	 */
	public void setRightHand(RightHandType value) {
		this.rightHand = value;
	}
	
	/**
	 * Gets the value of the leftHand property.
	 * 
	 * @return possible object is {@link LeftHandType }
	 */
	public LeftHandType getLeftHand() {
		return leftHand;
	}
	
	/**
	 * Sets the value of the leftHand property.
	 * 
	 * @param value allowed object is {@link LeftHandType }
	 */
	public void setLeftHand(LeftHandType value) {
		this.leftHand = value;
	}
	
}
