//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.03 at 12:50:15 PM WAT 
//

package org.openmrs.module.nigeriaemr.model.ndr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for HIVTestResultType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HIVTestResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestResult" type="{}TestResultType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RecencyTesting" type="{}RecencyTestingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HIVTestResultType", propOrder = { "testResult", "recencyTesting" })
public class HIVTestResultType {
	
	@XmlElement(name = "TestResult")
	protected List<TestResultType> testResult;
	
	@XmlElement(name = "RecencyTesting")
	protected List<RecencyTestingType> recencyTesting;
	
	/**
	 * Gets the value of the testResult property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the testResult property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
     *    getTestResult().add(newItem);
     * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TestResultType }
	 */
	public List<TestResultType> getTestResult() {
		if (testResult == null) {
			testResult = new ArrayList<TestResultType>();
		}
		return this.testResult;
	}
	
	/**
	 * Gets the value of the recencyTesting property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the recencyTesting property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
     *    getRecencyTesting().add(newItem);
     * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link RecencyTestingType }
	 */
	public List<RecencyTestingType> getRecencyTesting() {
		if (recencyTesting == null) {
			recencyTesting = new ArrayList<RecencyTestingType>();
		}
		return this.recencyTesting;
	}
	
}
