//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.01 at 01:38:46 PM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for MortalityType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MortalityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientVerification" type="{}ClientVerificationType" minOccurs="0"/>
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReasonForTracking" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="CoupTest"/>
 *               &lt;enumeration value="MissAppDate"/>
 *               &lt;enumeration value="MissPharmDate"/>
 *               &lt;enumeration value="Others"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherTrackingReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartnerFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressofTreatmentSupporter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateofLastActualContact" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DateofMissedScheduledAppointment" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DatePatientContacted" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="NameofPersonWhoAttemptedContact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModeofCommunication" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="MobilePhone"/>
 *               &lt;enumeration value="HomeVisit"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PersonContacted" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Patient"/>
 *               &lt;enumeration value="Guardian"/>
 *               &lt;enumeration value="TreatmentSupporter"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReasonforDefaulting" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Sick"/>
 *               &lt;enumeration value="LackofTransport"/>
 *               &lt;enumeration value="PatientForgottoAttendApp"/>
 *               &lt;enumeration value="FeltBetandStopedMed"/>
 *               &lt;enumeration value="NotPermtoLeaveWork"/>
 *               &lt;enumeration value="LostAppCard"/>
 *               &lt;enumeration value="StillHadDrugs"/>
 *               &lt;enumeration value="HerbalTradMeds"/>
 *               &lt;enumeration value="TreatmentSupporter"/>
 *               &lt;enumeration value="OthersSpecify"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherReasonforDefaulting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreviousARVExposure" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *               &lt;enumeration value="UNKNOWN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Discontinued" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="YES"/>
 *               &lt;enumeration value="NO"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateofTermination" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ReasonforTermination" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="TransferredOut"/>
 *               &lt;enumeration value="Death"/>
 *               &lt;enumeration value="Discontinued"/>
 *               &lt;enumeration value="TreatmentStop"/>
 *               &lt;enumeration value="SelfTransfer"/>
 *               &lt;enumeration value="DuplicateRecord"/>
 *               &lt;enumeration value="CouldNotVerifyClient"/>
 *               &lt;enumeration value="LTFU"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReasonforLosttoFollowup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="DidNotAttempttoTrackPatient"/>
 *               &lt;enumeration value="TrackedbutUnabletoLocate"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateReturnedtoCare" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ReffferedFor" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="AdherenceCounseling"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReffferedForOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DiscontinuedCare" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="ForcedDiscontinuation"/>
 *               &lt;enumeration value="MovedOutofArea"/>
 *               &lt;enumeration value="Other"/>
 *               &lt;enumeration value="SelfDiscontinuation"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DiscontinueCareOtherSpecify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransferredOutTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Death" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="OtherCauseofDeath"/>
 *               &lt;enumeration value="SuspectedARVSideEffect"/>
 *               &lt;enumeration value="SuspectedOpportunisticInfection"/>
 *               &lt;enumeration value="Unknown"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VACauseofDeath" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="VAAdultCasesofDeath"/>
 *               &lt;enumeration value="VAChildCasesofDeath"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherCauseofDeath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CauseOfDeath" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="AIDS"/>
 *               &lt;enumeration value="DiarrheaDysentery"/>
 *               &lt;enumeration value="Malaria"/>
 *               &lt;enumeration value="Maternal"/>
 *               &lt;enumeration value="OtherInfetiousDiseases"/>
 *               &lt;enumeration value="Pneumonia"/>
 *               &lt;enumeration value="TB"/>
 *               &lt;enumeration value="AcuteMyocardialInfection"/>
 *               &lt;enumeration value="BreastCancer"/>
 *               &lt;enumeration value="ChronicRespiratoryDiseases"/>
 *               &lt;enumeration value="CervicalCancer"/>
 *               &lt;enumeration value="Cirrhosis"/>
 *               &lt;enumeration value="ColorectalCancer"/>
 *               &lt;enumeration value="Diabetes"/>
 *               &lt;enumeration value="EsophagealCancer"/>
 *               &lt;enumeration value="LeukamiaLymphomas"/>
 *               &lt;enumeration value="LungCancer"/>
 *               &lt;enumeration value="OtherCardiovascularDiseases"/>
 *               &lt;enumeration value="OtherNonCommunicableDiseases"/>
 *               &lt;enumeration value="ProstateCancer"/>
 *               &lt;enumeration value="ChronicKidneyDisease"/>
 *               &lt;enumeration value="StomachCancer"/>
 *               &lt;enumeration value="Stroke"/>
 *               &lt;enumeration value="OtherCancers"/>
 *               &lt;enumeration value="BiteofVenomousAnimal"/>
 *               &lt;enumeration value="Drowning"/>
 *               &lt;enumeration value="Falls"/>
 *               &lt;enumeration value="Fires"/>
 *               &lt;enumeration value="Homicide"/>
 *               &lt;enumeration value="OtherInjuries"/>
 *               &lt;enumeration value="AccidentalPoisoning"/>
 *               &lt;enumeration value="RoadTraffic"/>
 *               &lt;enumeration value="SuicideByMultipleMeans"/>
 *               &lt;enumeration value="Encephalitis"/>
 *               &lt;enumeration value="HemorrhagicFever"/>
 *               &lt;enumeration value="Sepsis"/>
 *               &lt;enumeration value="Meningitis"/>
 *               &lt;enumeration value="Measles"/>
 *               &lt;enumeration value="OtherDefinedCausesofChildDeaths"/>
 *               &lt;enumeration value="OtherDigestiveDiseases"/>
 *               &lt;enumeration value="BirthAsphyxia"/>
 *               &lt;enumeration value="CongenitalMalformation"/>
 *               &lt;enumeration value="NeonatalMeningitis"/>
 *               &lt;enumeration value="NeonatalPneumonia"/>
 *               &lt;enumeration value="PretermDelivery"/>
 *               &lt;enumeration value="Stillbirth"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NameofContactTracer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactTrackerSignatureDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MortalityType", propOrder = { "clientVerification", "visitID", "visitDate", "reasonForTracking",
        "otherTrackingReason", "partnerFullName", "addressofTreatmentSupporter", "contactPhoneNumber",
        "dateofLastActualContact", "dateofMissedScheduledAppointment", "datePatientContacted",
        "nameofPersonWhoAttemptedContact", "modeofCommunication", "personContacted", "reasonforDefaulting",
        "otherReasonforDefaulting", "previousARVExposure", "discontinued", "dateofTermination", "reasonforTermination",
        "reasonforLosttoFollowup", "dateReturnedtoCare", "reffferedFor", "reffferedForOther", "discontinuedCare",
        "discontinueCareOtherSpecify", "transferredOutTo", "death", "vaCauseofDeath", "otherCauseofDeath", "causeOfDeath",
        "nameofContactTracer", "contactTrackerSignatureDate" })
public class MortalityType {
	
	@XmlElement(name = "ClientVerification")
	protected ClientVerificationType clientVerification;
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "ReasonForTracking")
	protected String reasonForTracking;
	
	@XmlElement(name = "OtherTrackingReason")
	protected String otherTrackingReason;
	
	@XmlElement(name = "PartnerFullName")
	protected String partnerFullName;
	
	@XmlElement(name = "AddressofTreatmentSupporter")
	protected String addressofTreatmentSupporter;
	
	@XmlElement(name = "ContactPhoneNumber")
	protected String contactPhoneNumber;
	
	@XmlElement(name = "DateofLastActualContact")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateofLastActualContact;
	
	@XmlElement(name = "DateofMissedScheduledAppointment")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateofMissedScheduledAppointment;
	
	@XmlElement(name = "DatePatientContacted")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar datePatientContacted;
	
	@XmlElement(name = "NameofPersonWhoAttemptedContact")
	protected String nameofPersonWhoAttemptedContact;
	
	@XmlElement(name = "ModeofCommunication")
	protected String modeofCommunication;
	
	@XmlElement(name = "PersonContacted")
	protected String personContacted;
	
	@XmlElement(name = "ReasonforDefaulting")
	protected String reasonforDefaulting;
	
	@XmlElement(name = "OtherReasonforDefaulting")
	protected String otherReasonforDefaulting;
	
	@XmlElement(name = "PreviousARVExposure")
	protected String previousARVExposure;
	
	@XmlElement(name = "Discontinued")
	protected String discontinued;
	
	@XmlElement(name = "DateofTermination")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateofTermination;
	
	@XmlElement(name = "ReasonforTermination")
	protected String reasonforTermination;
	
	@XmlElement(name = "ReasonforLosttoFollowup")
	protected String reasonforLosttoFollowup;
	
	@XmlElement(name = "DateReturnedtoCare")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateReturnedtoCare;
	
	@XmlElement(name = "ReffferedFor")
	protected String reffferedFor;
	
	@XmlElement(name = "ReffferedForOther")
	protected String reffferedForOther;
	
	@XmlElement(name = "DiscontinuedCare")
	protected String discontinuedCare;
	
	@XmlElement(name = "DiscontinueCareOtherSpecify")
	protected String discontinueCareOtherSpecify;
	
	@XmlElement(name = "TransferredOutTo")
	protected String transferredOutTo;
	
	@XmlElement(name = "Death")
	protected String death;
	
	@XmlElement(name = "VACauseofDeath")
	protected String vaCauseofDeath;
	
	@XmlElement(name = "OtherCauseofDeath")
	protected String otherCauseofDeath;
	
	@XmlElement(name = "CauseOfDeath")
	protected String causeOfDeath;
	
	@XmlElement(name = "NameofContactTracer")
	protected String nameofContactTracer;
	
	@XmlElement(name = "ContactTrackerSignatureDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar contactTrackerSignatureDate;
	
	/**
	 * Gets the value of the clientVerification property.
	 * 
	 * @return possible object is {@link ClientVerificationType }
	 */
	public ClientVerificationType getClientVerification() {
		return clientVerification;
	}
	
	/**
	 * Sets the value of the clientVerification property.
	 * 
	 * @param value allowed object is {@link ClientVerificationType }
	 */
	public void setClientVerification(ClientVerificationType value) {
		this.clientVerification = value;
	}
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the reasonForTracking property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonForTracking() {
		return reasonForTracking;
	}
	
	/**
	 * Sets the value of the reasonForTracking property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonForTracking(String value) {
		this.reasonForTracking = value;
	}
	
	/**
	 * Gets the value of the otherTrackingReason property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherTrackingReason() {
		return otherTrackingReason;
	}
	
	/**
	 * Sets the value of the otherTrackingReason property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherTrackingReason(String value) {
		this.otherTrackingReason = value;
	}
	
	/**
	 * Gets the value of the partnerFullName property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPartnerFullName() {
		return partnerFullName;
	}
	
	/**
	 * Sets the value of the partnerFullName property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPartnerFullName(String value) {
		this.partnerFullName = value;
	}
	
	/**
	 * Gets the value of the addressofTreatmentSupporter property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAddressofTreatmentSupporter() {
		return addressofTreatmentSupporter;
	}
	
	/**
	 * Sets the value of the addressofTreatmentSupporter property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAddressofTreatmentSupporter(String value) {
		this.addressofTreatmentSupporter = value;
	}
	
	/**
	 * Gets the value of the contactPhoneNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getContactPhoneNumber() {
		return contactPhoneNumber;
	}
	
	/**
	 * Sets the value of the contactPhoneNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setContactPhoneNumber(String value) {
		this.contactPhoneNumber = value;
	}
	
	/**
	 * Gets the value of the dateofLastActualContact property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateofLastActualContact() {
		return dateofLastActualContact;
	}
	
	/**
	 * Sets the value of the dateofLastActualContact property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateofLastActualContact(XMLGregorianCalendar value) {
		this.dateofLastActualContact = value;
	}
	
	/**
	 * Gets the value of the dateofMissedScheduledAppointment property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateofMissedScheduledAppointment() {
		return dateofMissedScheduledAppointment;
	}
	
	/**
	 * Sets the value of the dateofMissedScheduledAppointment property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateofMissedScheduledAppointment(XMLGregorianCalendar value) {
		this.dateofMissedScheduledAppointment = value;
	}
	
	/**
	 * Gets the value of the datePatientContacted property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDatePatientContacted() {
		return datePatientContacted;
	}
	
	/**
	 * Sets the value of the datePatientContacted property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDatePatientContacted(XMLGregorianCalendar value) {
		this.datePatientContacted = value;
	}
	
	/**
	 * Gets the value of the nameofPersonWhoAttemptedContact property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameofPersonWhoAttemptedContact() {
		return nameofPersonWhoAttemptedContact;
	}
	
	/**
	 * Sets the value of the nameofPersonWhoAttemptedContact property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameofPersonWhoAttemptedContact(String value) {
		this.nameofPersonWhoAttemptedContact = value;
	}
	
	/**
	 * Gets the value of the modeofCommunication property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getModeofCommunication() {
		return modeofCommunication;
	}
	
	/**
	 * Sets the value of the modeofCommunication property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setModeofCommunication(String value) {
		this.modeofCommunication = value;
	}
	
	/**
	 * Gets the value of the personContacted property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPersonContacted() {
		return personContacted;
	}
	
	/**
	 * Sets the value of the personContacted property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPersonContacted(String value) {
		this.personContacted = value;
	}
	
	/**
	 * Gets the value of the reasonforDefaulting property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonforDefaulting() {
		return reasonforDefaulting;
	}
	
	/**
	 * Sets the value of the reasonforDefaulting property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonforDefaulting(String value) {
		this.reasonforDefaulting = value;
	}
	
	/**
	 * Gets the value of the otherReasonforDefaulting property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherReasonforDefaulting() {
		return otherReasonforDefaulting;
	}
	
	/**
	 * Sets the value of the otherReasonforDefaulting property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherReasonforDefaulting(String value) {
		this.otherReasonforDefaulting = value;
	}
	
	/**
	 * Gets the value of the previousARVExposure property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPreviousARVExposure() {
		return previousARVExposure;
	}
	
	/**
	 * Sets the value of the previousARVExposure property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPreviousARVExposure(String value) {
		this.previousARVExposure = value;
	}
	
	/**
	 * Gets the value of the discontinued property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDiscontinued() {
		return discontinued;
	}
	
	/**
	 * Sets the value of the discontinued property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDiscontinued(String value) {
		this.discontinued = value;
	}
	
	/**
	 * Gets the value of the dateofTermination property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateofTermination() {
		return dateofTermination;
	}
	
	/**
	 * Sets the value of the dateofTermination property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateofTermination(XMLGregorianCalendar value) {
		this.dateofTermination = value;
	}
	
	/**
	 * Gets the value of the reasonforTermination property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonforTermination() {
		return reasonforTermination;
	}
	
	/**
	 * Sets the value of the reasonforTermination property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonforTermination(String value) {
		this.reasonforTermination = value;
	}
	
	/**
	 * Gets the value of the reasonforLosttoFollowup property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonforLosttoFollowup() {
		return reasonforLosttoFollowup;
	}
	
	/**
	 * Sets the value of the reasonforLosttoFollowup property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonforLosttoFollowup(String value) {
		this.reasonforLosttoFollowup = value;
	}
	
	/**
	 * Gets the value of the dateReturnedtoCare property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateReturnedtoCare() {
		return dateReturnedtoCare;
	}
	
	/**
	 * Sets the value of the dateReturnedtoCare property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateReturnedtoCare(XMLGregorianCalendar value) {
		this.dateReturnedtoCare = value;
	}
	
	/**
	 * Gets the value of the reffferedFor property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReffferedFor() {
		return reffferedFor;
	}
	
	/**
	 * Sets the value of the reffferedFor property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReffferedFor(String value) {
		this.reffferedFor = value;
	}
	
	/**
	 * Gets the value of the reffferedForOther property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReffferedForOther() {
		return reffferedForOther;
	}
	
	/**
	 * Sets the value of the reffferedForOther property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReffferedForOther(String value) {
		this.reffferedForOther = value;
	}
	
	/**
	 * Gets the value of the discontinuedCare property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDiscontinuedCare() {
		return discontinuedCare;
	}
	
	/**
	 * Sets the value of the discontinuedCare property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDiscontinuedCare(String value) {
		this.discontinuedCare = value;
	}
	
	/**
	 * Gets the value of the discontinueCareOtherSpecify property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDiscontinueCareOtherSpecify() {
		return discontinueCareOtherSpecify;
	}
	
	/**
	 * Sets the value of the discontinueCareOtherSpecify property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDiscontinueCareOtherSpecify(String value) {
		this.discontinueCareOtherSpecify = value;
	}
	
	/**
	 * Gets the value of the transferredOutTo property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTransferredOutTo() {
		return transferredOutTo;
	}
	
	/**
	 * Sets the value of the transferredOutTo property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTransferredOutTo(String value) {
		this.transferredOutTo = value;
	}
	
	/**
	 * Gets the value of the death property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDeath() {
		return death;
	}
	
	/**
	 * Sets the value of the death property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDeath(String value) {
		this.death = value;
	}
	
	/**
	 * Gets the value of the vaCauseofDeath property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVACauseofDeath() {
		return vaCauseofDeath;
	}
	
	/**
	 * Sets the value of the vaCauseofDeath property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVACauseofDeath(String value) {
		this.vaCauseofDeath = value;
	}
	
	/**
	 * Gets the value of the otherCauseofDeath property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherCauseofDeath() {
		return otherCauseofDeath;
	}
	
	/**
	 * Sets the value of the otherCauseofDeath property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherCauseofDeath(String value) {
		this.otherCauseofDeath = value;
	}
	
	/**
	 * Gets the value of the causeOfDeath property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCauseOfDeath() {
		return causeOfDeath;
	}
	
	/**
	 * Sets the value of the causeOfDeath property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setCauseOfDeath(String value) {
		this.causeOfDeath = value;
	}
	
	/**
	 * Gets the value of the nameofContactTracer property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameofContactTracer() {
		return nameofContactTracer;
	}
	
	/**
	 * Sets the value of the nameofContactTracer property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameofContactTracer(String value) {
		this.nameofContactTracer = value;
	}
	
	/**
	 * Gets the value of the contactTrackerSignatureDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getContactTrackerSignatureDate() {
		return contactTrackerSignatureDate;
	}
	
	/**
	 * Sets the value of the contactTrackerSignatureDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setContactTrackerSignatureDate(XMLGregorianCalendar value) {
		this.contactTrackerSignatureDate = value;
	}
	
}
