//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.05.12 at 09:38:23 PM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for RecencyType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TestName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="AS"/>
 *               &lt;enumeration value="OTH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RecencyNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ControlLine" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="VerificationLine" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="LongTermLine" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="RecencyInterpretation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Recent"/>
 *               &lt;enumeration value="Longterm"/>
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Invalid"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ViralLoadRequest" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="DateSampleCollected" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PCRLabNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SampleType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Plasma"/>
 *               &lt;enumeration value="DBS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateSampleSent" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PCRLab" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ViralLoadResultClassification" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="less_than_1000"/>
 *               &lt;enumeration value="greater_than_1000"/>
 *               &lt;enumeration value="Failed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HivViralLoad" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FinalRecencyTestResult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="RitaRecent"/>
 *               &lt;enumeration value="RitaLongterm"/>
 *               &lt;enumeration value="RitaInconclusive"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateConfirmedVL" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ViralLoadResult" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FinalRecencyResultInvestigation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="PR"/>
 *               &lt;enumeration value="CR"/>
 *               &lt;enumeration value="LT"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SourceDocumentUsed" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="EMR"/>
 *               &lt;enumeration value="Recency"/>
 *               &lt;enumeration value="HTS"/>
 *               &lt;enumeration value="Index"/>
 *               &lt;enumeration value="PNS"/>
 *               &lt;enumeration value="Tracking"/>
 *               &lt;enumeration value="Others"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LinkedToCare" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="DateLinkedToCare" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="InitiatedOnART" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="DateInitiatedOnART" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ARTNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Regimen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdherenceCounselling" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="recordedVL12Month" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="VLResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VlsSixMonth" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Yes"/>
 *               &lt;enumeration value="No"/>
 *               &lt;enumeration value="NA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PopulationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="KP"/>
 *               &lt;enumeration value="PP"/>
 *               &lt;enumeration value="GP"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubPopulationType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="SexWorkers"/>
 *               &lt;enumeration value="MSM"/>
 *               &lt;enumeration value="PWID"/>
 *               &lt;enumeration value="Transgender"/>
 *               &lt;enumeration value="AdolescentGirls"/>
 *               &lt;enumeration value="LDTD"/>
 *               &lt;enumeration value="Prisons"/>
 *               &lt;enumeration value="PregnantWomen"/>
 *               &lt;enumeration value="Others"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OfferedIndexTesting" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="ProvidedContacts" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="PartnerInformation" type="{}PartnerInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PatientReferred" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="PatientReferredClientCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecencyType", propOrder = { "visitID", "visitDate", "testName", "testDate", "recencyNumber", "controlLine",
        "verificationLine", "longTermLine", "recencyInterpretation", "viralLoadRequest", "dateSampleCollected",
        "pcrLabNumber", "sampleType", "dateSampleSent", "pcrLab", "viralLoadResultClassification", "hivViralLoad",
        "finalRecencyTestResult", "dateConfirmedVL", "viralLoadResult", "finalRecencyResultInvestigation",
        "sourceDocumentUsed", "linkedToCare", "dateLinkedToCare", "initiatedOnART", "dateInitiatedOnART", "artNumber",
        "regimen", "adherenceCounselling", "recordedVL12Month", "vlResult", "vlsSixMonth", "populationType",
        "subPopulationType", "offeredIndexTesting", "providedContacts", "partnerInformation", "patientReferred",
        "patientReferredClientCode" })
public class RecencyType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "TestName")
	protected String testName;
	
	@XmlElement(name = "TestDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar testDate;
	
	@XmlElement(name = "RecencyNumber", required = true)
	protected String recencyNumber;
	
	@XmlElement(name = "ControlLine")
	@XmlSchemaType(name = "string")
	protected YNCodeType controlLine;
	
	@XmlElement(name = "VerificationLine")
	@XmlSchemaType(name = "string")
	protected YNCodeType verificationLine;
	
	@XmlElement(name = "LongTermLine")
	@XmlSchemaType(name = "string")
	protected YNCodeType longTermLine;
	
	@XmlElement(name = "RecencyInterpretation")
	protected String recencyInterpretation;
	
	@XmlElement(name = "ViralLoadRequest")
	@XmlSchemaType(name = "string")
	protected YNCodeType viralLoadRequest;
	
	@XmlElement(name = "DateSampleCollected")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateSampleCollected;
	
	@XmlElement(name = "PCRLabNumber")
	protected String pcrLabNumber;
	
	@XmlElement(name = "SampleType")
	protected String sampleType;
	
	@XmlElement(name = "DateSampleSent")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateSampleSent;
	
	@XmlElement(name = "PCRLab")
	protected String pcrLab;
	
	@XmlElement(name = "ViralLoadResultClassification")
	protected String viralLoadResultClassification;
	
	@XmlElement(name = "HivViralLoad")
	protected Double hivViralLoad;
	
	@XmlElement(name = "FinalRecencyTestResult")
	protected String finalRecencyTestResult;
	
	@XmlElement(name = "DateConfirmedVL")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateConfirmedVL;
	
	@XmlElement(name = "ViralLoadResult")
	protected Double viralLoadResult;
	
	@XmlElement(name = "FinalRecencyResultInvestigation")
	protected String finalRecencyResultInvestigation;
	
	@XmlElement(name = "SourceDocumentUsed")
	protected List<String> sourceDocumentUsed;
	
	@XmlElement(name = "LinkedToCare")
	@XmlSchemaType(name = "string")
	protected YNCodeType linkedToCare;
	
	@XmlElement(name = "DateLinkedToCare")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateLinkedToCare;
	
	@XmlElement(name = "InitiatedOnART")
	@XmlSchemaType(name = "string")
	protected YNCodeType initiatedOnART;
	
	@XmlElement(name = "DateInitiatedOnART")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateInitiatedOnART;
	
	@XmlElement(name = "ARTNumber")
	protected String artNumber;
	
	@XmlElement(name = "Regimen")
	protected String regimen;
	
	@XmlElement(name = "AdherenceCounselling")
	@XmlSchemaType(name = "string")
	protected YNCodeType adherenceCounselling;
	
	@XmlSchemaType(name = "string")
	protected YNCodeType recordedVL12Month;
	
	@XmlElement(name = "VLResult")
	protected String vlResult;
	
	@XmlElement(name = "VlsSixMonth")
	protected String vlsSixMonth;
	
	@XmlElement(name = "PopulationType")
	protected String populationType;
	
	@XmlElement(name = "SubPopulationType")
	protected String subPopulationType;
	
	@XmlElement(name = "OfferedIndexTesting")
	@XmlSchemaType(name = "string")
	protected YNCodeType offeredIndexTesting;
	
	@XmlElement(name = "ProvidedContacts")
	@XmlSchemaType(name = "string")
	protected YNCodeType providedContacts;
	
	@XmlElement(name = "PartnerInformation")
	protected List<PartnerInformationType> partnerInformation;
	
	@XmlElement(name = "PatientReferred")
	@XmlSchemaType(name = "string")
	protected YNCodeType patientReferred;
	
	@XmlElement(name = "PatientReferredClientCode")
	protected String patientReferredClientCode;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the testName property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTestName() {
		return testName;
	}
	
	/**
	 * Sets the value of the testName property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTestName(String value) {
		this.testName = value;
	}
	
	/**
	 * Gets the value of the testDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getTestDate() {
		return testDate;
	}
	
	/**
	 * Sets the value of the testDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setTestDate(XMLGregorianCalendar value) {
		this.testDate = value;
	}
	
	/**
	 * Gets the value of the recencyNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRecencyNumber() {
		return recencyNumber;
	}
	
	/**
	 * Sets the value of the recencyNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRecencyNumber(String value) {
		this.recencyNumber = value;
	}
	
	/**
	 * Gets the value of the controlLine property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getControlLine() {
		return controlLine;
	}
	
	/**
	 * Sets the value of the controlLine property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setControlLine(YNCodeType value) {
		this.controlLine = value;
	}
	
	/**
	 * Gets the value of the verificationLine property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getVerificationLine() {
		return verificationLine;
	}
	
	/**
	 * Sets the value of the verificationLine property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setVerificationLine(YNCodeType value) {
		this.verificationLine = value;
	}
	
	/**
	 * Gets the value of the longTermLine property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getLongTermLine() {
		return longTermLine;
	}
	
	/**
	 * Sets the value of the longTermLine property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setLongTermLine(YNCodeType value) {
		this.longTermLine = value;
	}
	
	/**
	 * Gets the value of the recencyInterpretation property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRecencyInterpretation() {
		return recencyInterpretation;
	}
	
	/**
	 * Sets the value of the recencyInterpretation property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRecencyInterpretation(String value) {
		this.recencyInterpretation = value;
	}
	
	/**
	 * Gets the value of the viralLoadRequest property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getViralLoadRequest() {
		return viralLoadRequest;
	}
	
	/**
	 * Sets the value of the viralLoadRequest property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setViralLoadRequest(YNCodeType value) {
		this.viralLoadRequest = value;
	}
	
	/**
	 * Gets the value of the dateSampleCollected property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateSampleCollected() {
		return dateSampleCollected;
	}
	
	/**
	 * Sets the value of the dateSampleCollected property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateSampleCollected(XMLGregorianCalendar value) {
		this.dateSampleCollected = value;
	}
	
	/**
	 * Gets the value of the pcrLabNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPCRLabNumber() {
		return pcrLabNumber;
	}
	
	/**
	 * Sets the value of the pcrLabNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPCRLabNumber(String value) {
		this.pcrLabNumber = value;
	}
	
	/**
	 * Gets the value of the sampleType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSampleType() {
		return sampleType;
	}
	
	/**
	 * Sets the value of the sampleType property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSampleType(String value) {
		this.sampleType = value;
	}
	
	/**
	 * Gets the value of the dateSampleSent property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateSampleSent() {
		return dateSampleSent;
	}
	
	/**
	 * Sets the value of the dateSampleSent property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateSampleSent(XMLGregorianCalendar value) {
		this.dateSampleSent = value;
	}
	
	/**
	 * Gets the value of the pcrLab property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPCRLab() {
		return pcrLab;
	}
	
	/**
	 * Sets the value of the pcrLab property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPCRLab(String value) {
		this.pcrLab = value;
	}
	
	/**
	 * Gets the value of the viralLoadResultClassification property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getViralLoadResultClassification() {
		return viralLoadResultClassification;
	}
	
	/**
	 * Sets the value of the viralLoadResultClassification property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setViralLoadResultClassification(String value) {
		this.viralLoadResultClassification = value;
	}
	
	/**
	 * Gets the value of the hivViralLoad property.
	 * 
	 * @return possible object is {@link Double }
	 */
	public Double getHivViralLoad() {
		return hivViralLoad;
	}
	
	/**
	 * Sets the value of the hivViralLoad property.
	 * 
	 * @param value allowed object is {@link Double }
	 */
	public void setHivViralLoad(Double value) {
		this.hivViralLoad = value;
	}
	
	/**
	 * Gets the value of the finalRecencyTestResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getFinalRecencyTestResult() {
		return finalRecencyTestResult;
	}
	
	/**
	 * Sets the value of the finalRecencyTestResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setFinalRecencyTestResult(String value) {
		this.finalRecencyTestResult = value;
	}
	
	/**
	 * Gets the value of the dateConfirmedVL property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateConfirmedVL() {
		return dateConfirmedVL;
	}
	
	/**
	 * Sets the value of the dateConfirmedVL property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateConfirmedVL(XMLGregorianCalendar value) {
		this.dateConfirmedVL = value;
	}
	
	/**
	 * Gets the value of the viralLoadResult property.
	 * 
	 * @return possible object is {@link Double }
	 */
	public Double getViralLoadResult() {
		return viralLoadResult;
	}
	
	/**
	 * Sets the value of the viralLoadResult property.
	 * 
	 * @param value allowed object is {@link Double }
	 */
	public void setViralLoadResult(Double value) {
		this.viralLoadResult = value;
	}
	
	/**
	 * Gets the value of the finalRecencyResultInvestigation property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getFinalRecencyResultInvestigation() {
		return finalRecencyResultInvestigation;
	}
	
	/**
	 * Sets the value of the finalRecencyResultInvestigation property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setFinalRecencyResultInvestigation(String value) {
		this.finalRecencyResultInvestigation = value;
	}
	
	/**
	 * Gets the value of the sourceDocumentUsed property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the sourceDocumentUsed property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 *    getSourceDocumentUsed().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 */
	public List<String> getSourceDocumentUsed() {
		if (sourceDocumentUsed == null) {
			sourceDocumentUsed = new ArrayList<String>();
		}
		return this.sourceDocumentUsed;
	}
	
	/**
	 * Gets the value of the linkedToCare property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getLinkedToCare() {
		return linkedToCare;
	}
	
	/**
	 * Sets the value of the linkedToCare property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setLinkedToCare(YNCodeType value) {
		this.linkedToCare = value;
	}
	
	/**
	 * Gets the value of the dateLinkedToCare property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateLinkedToCare() {
		return dateLinkedToCare;
	}
	
	/**
	 * Sets the value of the dateLinkedToCare property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateLinkedToCare(XMLGregorianCalendar value) {
		this.dateLinkedToCare = value;
	}
	
	/**
	 * Gets the value of the initiatedOnART property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getInitiatedOnART() {
		return initiatedOnART;
	}
	
	/**
	 * Sets the value of the initiatedOnART property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setInitiatedOnART(YNCodeType value) {
		this.initiatedOnART = value;
	}
	
	/**
	 * Gets the value of the dateInitiatedOnART property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateInitiatedOnART() {
		return dateInitiatedOnART;
	}
	
	/**
	 * Sets the value of the dateInitiatedOnART property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateInitiatedOnART(XMLGregorianCalendar value) {
		this.dateInitiatedOnART = value;
	}
	
	/**
	 * Gets the value of the artNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getARTNumber() {
		return artNumber;
	}
	
	/**
	 * Sets the value of the artNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setARTNumber(String value) {
		this.artNumber = value;
	}
	
	/**
	 * Gets the value of the regimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRegimen() {
		return regimen;
	}
	
	/**
	 * Sets the value of the regimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRegimen(String value) {
		this.regimen = value;
	}
	
	/**
	 * Gets the value of the adherenceCounselling property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getAdherenceCounselling() {
		return adherenceCounselling;
	}
	
	/**
	 * Sets the value of the adherenceCounselling property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setAdherenceCounselling(YNCodeType value) {
		this.adherenceCounselling = value;
	}
	
	/**
	 * Gets the value of the recordedVL12Month property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getRecordedVL12Month() {
		return recordedVL12Month;
	}
	
	/**
	 * Sets the value of the recordedVL12Month property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setRecordedVL12Month(YNCodeType value) {
		this.recordedVL12Month = value;
	}
	
	/**
	 * Gets the value of the vlResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVLResult() {
		return vlResult;
	}
	
	/**
	 * Sets the value of the vlResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVLResult(String value) {
		this.vlResult = value;
	}
	
	/**
	 * Gets the value of the vlsSixMonth property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVlsSixMonth() {
		return vlsSixMonth;
	}
	
	/**
	 * Sets the value of the vlsSixMonth property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVlsSixMonth(String value) {
		this.vlsSixMonth = value;
	}
	
	/**
	 * Gets the value of the populationType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPopulationType() {
		return populationType;
	}
	
	/**
	 * Sets the value of the populationType property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPopulationType(String value) {
		this.populationType = value;
	}
	
	/**
	 * Gets the value of the subPopulationType property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the subPopulationType property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 *    getSubPopulationType().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * @return
	 */
	
	public String getSubPopulationType() {
		return subPopulationType;
	}
	
	public void setSubPopulationType(String value) {
		this.subPopulationType = value;
	}
	
	/**
	 * Gets the value of the offeredIndexTesting property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getOfferedIndexTesting() {
		return offeredIndexTesting;
	}
	
	/**
	 * Sets the value of the offeredIndexTesting property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setOfferedIndexTesting(YNCodeType value) {
		this.offeredIndexTesting = value;
	}
	
	/**
	 * Gets the value of the providedContacts property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getProvidedContacts() {
		return providedContacts;
	}
	
	/**
	 * Sets the value of the providedContacts property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setProvidedContacts(YNCodeType value) {
		this.providedContacts = value;
	}
	
	/**
	 * Gets the value of the partnerInformation property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the partnerInformation property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 *    getPartnerInformation().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link PartnerInformationType }
	 */
	public List<PartnerInformationType> getPartnerInformation() {
		if (partnerInformation == null) {
			partnerInformation = new ArrayList<PartnerInformationType>();
		}
		return this.partnerInformation;
	}
	
	public void setPartnerInformation(List<PartnerInformationType> partnerInformation) {
		this.partnerInformation = partnerInformation;
	}
	
	/**
	 * Gets the value of the patientReferred property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getPatientReferred() {
		return patientReferred;
	}
	
	/**
	 * Sets the value of the patientReferred property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setPatientReferred(YNCodeType value) {
		this.patientReferred = value;
	}
	
	/**
	 * Gets the value of the patientReferredClientCode property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPatientReferredClientCode() {
		return patientReferredClientCode;
	}
	
	/**
	 * Sets the value of the patientReferredClientCode property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPatientReferredClientCode(String value) {
		this.patientReferredClientCode = value;
	}
	
}
