//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.01 at 09:42:41 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for SpecimenExaminationResultFormType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecimenExaminationResultFormType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{}StringType"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NameOfRequestingHealthFacility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateOfRequestingHealthFacility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LGAOrTBNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfLaboratory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LaboratorySerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MTBNotDetected" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="OtherTestTypeSpecified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultsOfOtherTest" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Positive"/>
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Intermediate"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateAFBSmearSampleReceived" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Specimen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Appearance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Result" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Scanty"/>
 *               &lt;enumeration value="OnePlus"/>
 *               &lt;enumeration value="TwoPlus"/>
 *               &lt;enumeration value="ThreePlus"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AFBSmearResultExaminedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfAFBSmearMicroscopyResult" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TypeOfCultureResult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="BaselineCulture"/>
 *               &lt;enumeration value="FollowUp"/>
 *               &lt;enumeration value="MonthOfFollowUp"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateCultureSampleReceived" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CultureSpecimen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SolidCultureResult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Scanty"/>
 *               &lt;enumeration value="OnePlus"/>
 *               &lt;enumeration value="TwoPlus"/>
 *               &lt;enumeration value="ThreePlus"/>
 *               &lt;enumeration value="Contaminated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LiquidCultureResult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Positive"/>
 *               &lt;enumeration value="Contaminated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ResultOfConfirmatoryTestForMTB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CultureExaminedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CultureDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TypeOfLPAOrDSTMethodUsed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="LPA"/>
 *               &lt;enumeration value="SolidCultureDST"/>
 *               &lt;enumeration value="LiquidCultureDST"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateSampleReceived" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="LPASpecimen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LPAResults" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Resistant"/>
 *               &lt;enumeration value="Susceptible"/>
 *               &lt;enumeration value="Indeterminate"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LPADrugs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Rifampicin"/>
 *               &lt;enumeration value="Isoniazid"/>
 *               &lt;enumeration value="FluoroquilinoneOrCyclic"/>
 *               &lt;enumeration value="LowLevelKanamycin"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DSTResults" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Resistant"/>
 *               &lt;enumeration value="Susceptible"/>
 *               &lt;enumeration value="Contaminated"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DSTDrugs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Rifampicin"/>
 *               &lt;enumeration value="Isoniazid"/>
 *               &lt;enumeration value="Ethambuthol"/>
 *               &lt;enumeration value="Pyrazinamide"/>
 *               &lt;enumeration value="Kanamycin"/>
 *               &lt;enumeration value="Capreomycin"/>
 *               &lt;enumeration value="Amikacin"/>
 *               &lt;enumeration value="Levofloxacin"/>
 *               &lt;enumeration value="Moxifloxacin"/>
 *               &lt;enumeration value="ProtionamideOrEtionamide"/>
 *               &lt;enumeration value="CycloserineOrTerizidone"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DSTExaminedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DSTDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Remark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HIVTestResult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Indeterminate"/>
 *               &lt;enumeration value="Negative"/>
 *               &lt;enumeration value="Positive"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HIVTestResultDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ResultCheckedAndReleasedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecimenExaminationResultFormType", propOrder = { "visitID", "visitDate", "nameOfRequestingHealthFacility",
        "stateOfRequestingHealthFacility", "lgaOrTBNumber", "nameOfLaboratory", "laboratorySerialNumber", "mtbNotDetected",
        "otherTestTypeSpecified", "resultsOfOtherTest", "dateAFBSmearSampleReceived", "specimen", "appearance", "result",
        "afbSmearResultExaminedBy", "dateOfAFBSmearMicroscopyResult", "typeOfCultureResult", "dateCultureSampleReceived",
        "cultureSpecimen", "solidCultureResult", "liquidCultureResult", "resultOfConfirmatoryTestForMTB",
        "cultureExaminedBy", "cultureDate", "typeOfLPAOrDSTMethodUsed", "dateSampleReceived", "lpaSpecimen", "lpaResults",
        "lpaDrugs", "dstResults", "dstDrugs", "dstExaminedBy", "dstDate", "remark", "hivTestResult", "hivTestResultDate",
        "resultCheckedAndReleasedBy" })
public class SpecimenExaminationResultFormType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "NameOfRequestingHealthFacility")
	protected String nameOfRequestingHealthFacility;
	
	@XmlElement(name = "StateOfRequestingHealthFacility")
	protected String stateOfRequestingHealthFacility;
	
	@XmlElement(name = "LGAOrTBNumber", required = true)
	protected String lgaOrTBNumber;
	
	@XmlElement(name = "NameOfLaboratory")
	protected String nameOfLaboratory;
	
	@XmlElement(name = "LaboratorySerialNumber")
	protected String laboratorySerialNumber;
	
	@XmlElement(name = "MTBNotDetected")
	@XmlSchemaType(name = "string")
	protected YNCodeType mtbNotDetected;
	
	@XmlElement(name = "OtherTestTypeSpecified")
	protected String otherTestTypeSpecified;
	
	@XmlElement(name = "ResultsOfOtherTest")
	protected String resultsOfOtherTest;
	
	@XmlElement(name = "DateAFBSmearSampleReceived")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateAFBSmearSampleReceived;
	
	@XmlElement(name = "Specimen")
	protected String specimen;
	
	@XmlElement(name = "Appearance")
	protected String appearance;
	
	@XmlElement(name = "Result")
	protected String result;
	
	@XmlElement(name = "AFBSmearResultExaminedBy")
	protected String afbSmearResultExaminedBy;
	
	@XmlElement(name = "DateOfAFBSmearMicroscopyResult")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateOfAFBSmearMicroscopyResult;
	
	@XmlElement(name = "TypeOfCultureResult")
	protected String typeOfCultureResult;
	
	@XmlElement(name = "DateCultureSampleReceived")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateCultureSampleReceived;
	
	@XmlElement(name = "CultureSpecimen")
	protected String cultureSpecimen;
	
	@XmlElement(name = "SolidCultureResult")
	protected String solidCultureResult;
	
	@XmlElement(name = "LiquidCultureResult")
	protected String liquidCultureResult;
	
	@XmlElement(name = "ResultOfConfirmatoryTestForMTB")
	protected String resultOfConfirmatoryTestForMTB;
	
	@XmlElement(name = "CultureExaminedBy")
	protected String cultureExaminedBy;
	
	@XmlElement(name = "CultureDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar cultureDate;
	
	@XmlElement(name = "TypeOfLPAOrDSTMethodUsed")
	protected String typeOfLPAOrDSTMethodUsed;
	
	@XmlElement(name = "DateSampleReceived")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateSampleReceived;
	
	@XmlElement(name = "LPASpecimen")
	protected String lpaSpecimen;
	
	@XmlElement(name = "LPAResults")
	protected String lpaResults;
	
	@XmlElement(name = "LPADrugs")
	protected String lpaDrugs;
	
	@XmlElement(name = "DSTResults")
	protected String dstResults;
	
	@XmlElement(name = "DSTDrugs")
	protected String dstDrugs;
	
	@XmlElement(name = "DSTExaminedBy")
	protected String dstExaminedBy;
	
	@XmlElement(name = "DSTDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dstDate;
	
	@XmlElement(name = "Remark")
	protected String remark;
	
	@XmlElement(name = "HIVTestResult")
	protected String hivTestResult;
	
	@XmlElement(name = "HIVTestResultDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar hivTestResultDate;
	
	@XmlElement(name = "ResultCheckedAndReleasedBy")
	protected String resultCheckedAndReleasedBy;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the nameOfRequestingHealthFacility property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameOfRequestingHealthFacility() {
		return nameOfRequestingHealthFacility;
	}
	
	/**
	 * Sets the value of the nameOfRequestingHealthFacility property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameOfRequestingHealthFacility(String value) {
		this.nameOfRequestingHealthFacility = value;
	}
	
	/**
	 * Gets the value of the stateOfRequestingHealthFacility property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getStateOfRequestingHealthFacility() {
		return stateOfRequestingHealthFacility;
	}
	
	/**
	 * Sets the value of the stateOfRequestingHealthFacility property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setStateOfRequestingHealthFacility(String value) {
		this.stateOfRequestingHealthFacility = value;
	}
	
	/**
	 * Gets the value of the lgaOrTBNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLGAOrTBNumber() {
		return lgaOrTBNumber;
	}
	
	/**
	 * Sets the value of the lgaOrTBNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLGAOrTBNumber(String value) {
		this.lgaOrTBNumber = value;
	}
	
	/**
	 * Gets the value of the nameOfLaboratory property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameOfLaboratory() {
		return nameOfLaboratory;
	}
	
	/**
	 * Sets the value of the nameOfLaboratory property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameOfLaboratory(String value) {
		this.nameOfLaboratory = value;
	}
	
	/**
	 * Gets the value of the laboratorySerialNumber property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLaboratorySerialNumber() {
		return laboratorySerialNumber;
	}
	
	/**
	 * Sets the value of the laboratorySerialNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLaboratorySerialNumber(String value) {
		this.laboratorySerialNumber = value;
	}
	
	/**
	 * Gets the value of the mtbNotDetected property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getMTBNotDetected() {
		return mtbNotDetected;
	}
	
	/**
	 * Sets the value of the mtbNotDetected property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setMTBNotDetected(YNCodeType value) {
		this.mtbNotDetected = value;
	}
	
	/**
	 * Gets the value of the otherTestTypeSpecified property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherTestTypeSpecified() {
		return otherTestTypeSpecified;
	}
	
	/**
	 * Sets the value of the otherTestTypeSpecified property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherTestTypeSpecified(String value) {
		this.otherTestTypeSpecified = value;
	}
	
	/**
	 * Gets the value of the resultsOfOtherTest property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getResultsOfOtherTest() {
		return resultsOfOtherTest;
	}
	
	/**
	 * Sets the value of the resultsOfOtherTest property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setResultsOfOtherTest(String value) {
		this.resultsOfOtherTest = value;
	}
	
	/**
	 * Gets the value of the dateAFBSmearSampleReceived property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateAFBSmearSampleReceived() {
		return dateAFBSmearSampleReceived;
	}
	
	/**
	 * Sets the value of the dateAFBSmearSampleReceived property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateAFBSmearSampleReceived(XMLGregorianCalendar value) {
		this.dateAFBSmearSampleReceived = value;
	}
	
	/**
	 * Gets the value of the specimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSpecimen() {
		return specimen;
	}
	
	/**
	 * Sets the value of the specimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSpecimen(String value) {
		this.specimen = value;
	}
	
	/**
	 * Gets the value of the appearance property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAppearance() {
		return appearance;
	}
	
	/**
	 * Sets the value of the appearance property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAppearance(String value) {
		this.appearance = value;
	}
	
	/**
	 * Gets the value of the result property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getResult() {
		return result;
	}
	
	/**
	 * Sets the value of the result property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setResult(String value) {
		this.result = value;
	}
	
	/**
	 * Gets the value of the afbSmearResultExaminedBy property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAFBSmearResultExaminedBy() {
		return afbSmearResultExaminedBy;
	}
	
	/**
	 * Sets the value of the afbSmearResultExaminedBy property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAFBSmearResultExaminedBy(String value) {
		this.afbSmearResultExaminedBy = value;
	}
	
	/**
	 * Gets the value of the dateOfAFBSmearMicroscopyResult property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateOfAFBSmearMicroscopyResult() {
		return dateOfAFBSmearMicroscopyResult;
	}
	
	/**
	 * Sets the value of the dateOfAFBSmearMicroscopyResult property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateOfAFBSmearMicroscopyResult(XMLGregorianCalendar value) {
		this.dateOfAFBSmearMicroscopyResult = value;
	}
	
	/**
	 * Gets the value of the typeOfCultureResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTypeOfCultureResult() {
		return typeOfCultureResult;
	}
	
	/**
	 * Sets the value of the typeOfCultureResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTypeOfCultureResult(String value) {
		this.typeOfCultureResult = value;
	}
	
	/**
	 * Gets the value of the dateCultureSampleReceived property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateCultureSampleReceived() {
		return dateCultureSampleReceived;
	}
	
	/**
	 * Sets the value of the dateCultureSampleReceived property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateCultureSampleReceived(XMLGregorianCalendar value) {
		this.dateCultureSampleReceived = value;
	}
	
	/**
	 * Gets the value of the cultureSpecimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCultureSpecimen() {
		return cultureSpecimen;
	}
	
	/**
	 * Sets the value of the cultureSpecimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setCultureSpecimen(String value) {
		this.cultureSpecimen = value;
	}
	
	/**
	 * Gets the value of the solidCultureResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSolidCultureResult() {
		return solidCultureResult;
	}
	
	/**
	 * Sets the value of the solidCultureResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSolidCultureResult(String value) {
		this.solidCultureResult = value;
	}
	
	/**
	 * Gets the value of the liquidCultureResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLiquidCultureResult() {
		return liquidCultureResult;
	}
	
	/**
	 * Sets the value of the liquidCultureResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLiquidCultureResult(String value) {
		this.liquidCultureResult = value;
	}
	
	/**
	 * Gets the value of the resultOfConfirmatoryTestForMTB property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getResultOfConfirmatoryTestForMTB() {
		return resultOfConfirmatoryTestForMTB;
	}
	
	/**
	 * Sets the value of the resultOfConfirmatoryTestForMTB property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setResultOfConfirmatoryTestForMTB(String value) {
		this.resultOfConfirmatoryTestForMTB = value;
	}
	
	/**
	 * Gets the value of the cultureExaminedBy property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getCultureExaminedBy() {
		return cultureExaminedBy;
	}
	
	/**
	 * Sets the value of the cultureExaminedBy property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setCultureExaminedBy(String value) {
		this.cultureExaminedBy = value;
	}
	
	/**
	 * Gets the value of the cultureDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getCultureDate() {
		return cultureDate;
	}
	
	/**
	 * Sets the value of the cultureDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setCultureDate(XMLGregorianCalendar value) {
		this.cultureDate = value;
	}
	
	/**
	 * Gets the value of the typeOfLPAOrDSTMethodUsed property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTypeOfLPAOrDSTMethodUsed() {
		return typeOfLPAOrDSTMethodUsed;
	}
	
	/**
	 * Sets the value of the typeOfLPAOrDSTMethodUsed property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTypeOfLPAOrDSTMethodUsed(String value) {
		this.typeOfLPAOrDSTMethodUsed = value;
	}
	
	/**
	 * Gets the value of the dateSampleReceived property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateSampleReceived() {
		return dateSampleReceived;
	}
	
	/**
	 * Sets the value of the dateSampleReceived property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateSampleReceived(XMLGregorianCalendar value) {
		this.dateSampleReceived = value;
	}
	
	/**
	 * Gets the value of the lpaSpecimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLPASpecimen() {
		return lpaSpecimen;
	}
	
	/**
	 * Sets the value of the lpaSpecimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLPASpecimen(String value) {
		this.lpaSpecimen = value;
	}
	
	/**
	 * Gets the value of the lpaResults property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLPAResults() {
		return lpaResults;
	}
	
	/**
	 * Sets the value of the lpaResults property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLPAResults(String value) {
		this.lpaResults = value;
	}
	
	/**
	 * Gets the value of the lpaDrugs property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLPADrugs() {
		return lpaDrugs;
	}
	
	/**
	 * Sets the value of the lpaDrugs property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setLPADrugs(String value) {
		this.lpaDrugs = value;
	}
	
	/**
	 * Gets the value of the dstResults property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDSTResults() {
		return dstResults;
	}
	
	/**
	 * Sets the value of the dstResults property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDSTResults(String value) {
		this.dstResults = value;
	}
	
	/**
	 * Gets the value of the dstDrugs property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDSTDrugs() {
		return dstDrugs;
	}
	
	/**
	 * Sets the value of the dstDrugs property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDSTDrugs(String value) {
		this.dstDrugs = value;
	}
	
	/**
	 * Gets the value of the dstExaminedBy property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDSTExaminedBy() {
		return dstExaminedBy;
	}
	
	/**
	 * Sets the value of the dstExaminedBy property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDSTExaminedBy(String value) {
		this.dstExaminedBy = value;
	}
	
	/**
	 * Gets the value of the dstDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDSTDate() {
		return dstDate;
	}
	
	/**
	 * Sets the value of the dstDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDSTDate(XMLGregorianCalendar value) {
		this.dstDate = value;
	}
	
	/**
	 * Gets the value of the remark property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getRemark() {
		return remark;
	}
	
	/**
	 * Sets the value of the remark property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setRemark(String value) {
		this.remark = value;
	}
	
	/**
	 * Gets the value of the hivTestResult property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getHIVTestResult() {
		return hivTestResult;
	}
	
	/**
	 * Sets the value of the hivTestResult property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setHIVTestResult(String value) {
		this.hivTestResult = value;
	}
	
	/**
	 * Gets the value of the hivTestResultDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getHIVTestResultDate() {
		return hivTestResultDate;
	}
	
	/**
	 * Sets the value of the hivTestResultDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setHIVTestResultDate(XMLGregorianCalendar value) {
		this.hivTestResultDate = value;
	}
	
	/**
	 * Gets the value of the resultCheckedAndReleasedBy property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getResultCheckedAndReleasedBy() {
		return resultCheckedAndReleasedBy;
	}
	
	/**
	 * Sets the value of the resultCheckedAndReleasedBy property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setResultCheckedAndReleasedBy(String value) {
		this.resultCheckedAndReleasedBy = value;
	}
	
}
