//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.01 at 09:42:41 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TBCommunityAndFacilityReferralType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBCommunityAndFacilityReferralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReferringFacility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateofReferral" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AddressofReferringOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameOfReferringPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneNumberOfRefferingOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReasonForReferral" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="TuberculosisDiagnosisClassification"/>
 *               &lt;enumeration value="Treatment"/>
 *               &lt;enumeration value="AdverseEffect"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherCoMorbidity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProfileOfReferringPerson" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="CommunityTBWorker"/>
 *               &lt;enumeration value="CommunityVolunteer"/>
 *               &lt;enumeration value="CommunityInformant"/>
 *               &lt;enumeration value="CommunityPharmacy"/>
 *               &lt;enumeration value="PatentMedicineShop"/>
 *               &lt;enumeration value="TraditionalBirthAttendant"/>
 *               &lt;enumeration value="HealthLaboratoryWorker"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherProfileOfReferringPersonSpecify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReceivingOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateOfArrivalAtReferredOrganization" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="NameOfHealthWorkerAtReceivingOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OutcomeOfReferral" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="TBConfirmed"/>
 *               &lt;enumeration value="TBNotConfirmed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PhoneNumberOfRecivingOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TBTreatmentOutcomeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TBDrugTreatmentStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TBCommunityAndFacilityReferralDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBCommunityAndFacilityReferralType", propOrder = { "visitID", "visitDate", "referringFacility",
        "dateofReferral", "addressofReferringOrganization", "nameOfReferringPerson", "phoneNumberOfRefferingOrganization",
        "reasonForReferral", "otherCoMorbidity", "profileOfReferringPerson", "otherProfileOfReferringPersonSpecify",
        "receivingOrganization", "dateOfArrivalAtReferredOrganization", "nameOfHealthWorkerAtReceivingOrganization",
        "outcomeOfReferral", "phoneNumberOfRecivingOrganization", "tbTreatmentOutcomeDate", "tbDrugTreatmentStartDate" })
public class TBCommunityAndFacilityReferralType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "ReferringFacility", required = true)
	protected String referringFacility;
	
	@XmlElement(name = "DateofReferral")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateofReferral;
	
	@XmlElement(name = "AddressofReferringOrganization")
	protected String addressofReferringOrganization;
	
	@XmlElement(name = "NameOfReferringPerson")
	protected String nameOfReferringPerson;
	
	@XmlElement(name = "PhoneNumberOfRefferingOrganization")
	protected String phoneNumberOfRefferingOrganization;
	
	@XmlElement(name = "ReasonForReferral")
	protected String reasonForReferral;
	
	@XmlElement(name = "OtherCoMorbidity")
	protected String otherCoMorbidity;
	
	@XmlElement(name = "ProfileOfReferringPerson")
	protected String profileOfReferringPerson;
	
	@XmlElement(name = "OtherProfileOfReferringPersonSpecify")
	protected String otherProfileOfReferringPersonSpecify;
	
	@XmlElement(name = "ReceivingOrganization", required = true)
	protected String receivingOrganization;
	
	@XmlElement(name = "DateOfArrivalAtReferredOrganization")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateOfArrivalAtReferredOrganization;
	
	@XmlElement(name = "NameOfHealthWorkerAtReceivingOrganization", required = true)
	protected String nameOfHealthWorkerAtReceivingOrganization;
	
	@XmlElement(name = "OutcomeOfReferral")
	protected String outcomeOfReferral;
	
	@XmlElement(name = "PhoneNumberOfRecivingOrganization")
	protected String phoneNumberOfRecivingOrganization;
	
	@XmlElement(name = "TBTreatmentOutcomeDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar tbTreatmentOutcomeDate;
	
	@XmlElement(name = "TBDrugTreatmentStartDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar tbDrugTreatmentStartDate;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the referringFacility property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReferringFacility() {
		return referringFacility;
	}
	
	/**
	 * Sets the value of the referringFacility property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReferringFacility(String value) {
		this.referringFacility = value;
	}
	
	/**
	 * Gets the value of the dateofReferral property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateofReferral() {
		return dateofReferral;
	}
	
	/**
	 * Sets the value of the dateofReferral property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateofReferral(XMLGregorianCalendar value) {
		this.dateofReferral = value;
	}
	
	/**
	 * Gets the value of the addressofReferringOrganization property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getAddressofReferringOrganization() {
		return addressofReferringOrganization;
	}
	
	/**
	 * Sets the value of the addressofReferringOrganization property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setAddressofReferringOrganization(String value) {
		this.addressofReferringOrganization = value;
	}
	
	/**
	 * Gets the value of the nameOfReferringPerson property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameOfReferringPerson() {
		return nameOfReferringPerson;
	}
	
	/**
	 * Sets the value of the nameOfReferringPerson property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameOfReferringPerson(String value) {
		this.nameOfReferringPerson = value;
	}
	
	/**
	 * Gets the value of the phoneNumberOfRefferingOrganization property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPhoneNumberOfRefferingOrganization() {
		return phoneNumberOfRefferingOrganization;
	}
	
	/**
	 * Sets the value of the phoneNumberOfRefferingOrganization property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPhoneNumberOfRefferingOrganization(String value) {
		this.phoneNumberOfRefferingOrganization = value;
	}
	
	/**
	 * Gets the value of the reasonForReferral property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonForReferral() {
		return reasonForReferral;
	}
	
	/**
	 * Sets the value of the reasonForReferral property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonForReferral(String value) {
		this.reasonForReferral = value;
	}
	
	/**
	 * Gets the value of the otherCoMorbidity property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherCoMorbidity() {
		return otherCoMorbidity;
	}
	
	/**
	 * Sets the value of the otherCoMorbidity property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherCoMorbidity(String value) {
		this.otherCoMorbidity = value;
	}
	
	/**
	 * Gets the value of the profileOfReferringPerson property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getProfileOfReferringPerson() {
		return profileOfReferringPerson;
	}
	
	/**
	 * Sets the value of the profileOfReferringPerson property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setProfileOfReferringPerson(String value) {
		this.profileOfReferringPerson = value;
	}
	
	/**
	 * Gets the value of the otherProfileOfReferringPersonSpecify property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherProfileOfReferringPersonSpecify() {
		return otherProfileOfReferringPersonSpecify;
	}
	
	/**
	 * Sets the value of the otherProfileOfReferringPersonSpecify property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherProfileOfReferringPersonSpecify(String value) {
		this.otherProfileOfReferringPersonSpecify = value;
	}
	
	/**
	 * Gets the value of the receivingOrganization property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReceivingOrganization() {
		return receivingOrganization;
	}
	
	/**
	 * Sets the value of the receivingOrganization property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReceivingOrganization(String value) {
		this.receivingOrganization = value;
	}
	
	/**
	 * Gets the value of the dateOfArrivalAtReferredOrganization property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateOfArrivalAtReferredOrganization() {
		return dateOfArrivalAtReferredOrganization;
	}
	
	/**
	 * Sets the value of the dateOfArrivalAtReferredOrganization property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateOfArrivalAtReferredOrganization(XMLGregorianCalendar value) {
		this.dateOfArrivalAtReferredOrganization = value;
	}
	
	/**
	 * Gets the value of the nameOfHealthWorkerAtReceivingOrganization property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getNameOfHealthWorkerAtReceivingOrganization() {
		return nameOfHealthWorkerAtReceivingOrganization;
	}
	
	/**
	 * Sets the value of the nameOfHealthWorkerAtReceivingOrganization property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setNameOfHealthWorkerAtReceivingOrganization(String value) {
		this.nameOfHealthWorkerAtReceivingOrganization = value;
	}
	
	/**
	 * Gets the value of the outcomeOfReferral property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOutcomeOfReferral() {
		return outcomeOfReferral;
	}
	
	/**
	 * Sets the value of the outcomeOfReferral property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOutcomeOfReferral(String value) {
		this.outcomeOfReferral = value;
	}
	
	/**
	 * Gets the value of the phoneNumberOfRecivingOrganization property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPhoneNumberOfRecivingOrganization() {
		return phoneNumberOfRecivingOrganization;
	}
	
	/**
	 * Sets the value of the phoneNumberOfRecivingOrganization property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPhoneNumberOfRecivingOrganization(String value) {
		this.phoneNumberOfRecivingOrganization = value;
	}
	
	/**
	 * Gets the value of the tbTreatmentOutcomeDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getTBTreatmentOutcomeDate() {
		return tbTreatmentOutcomeDate;
	}
	
	/**
	 * Sets the value of the tbTreatmentOutcomeDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setTBTreatmentOutcomeDate(XMLGregorianCalendar value) {
		this.tbTreatmentOutcomeDate = value;
	}
	
	/**
	 * Gets the value of the tbDrugTreatmentStartDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getTBDrugTreatmentStartDate() {
		return tbDrugTreatmentStartDate;
	}
	
	/**
	 * Sets the value of the tbDrugTreatmentStartDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setTBDrugTreatmentStartDate(XMLGregorianCalendar value) {
		this.tbDrugTreatmentStartDate = value;
	}
	
}
