//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.01 at 09:42:41 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TBInterruptionTrackingType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBInterruptionTrackingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TrackingAttempts" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="FirstAttempt"/>
 *               &lt;enumeration value="SecondAttempt"/>
 *               &lt;enumeration value="ThirdAttempt"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DateOfLastDrugIntake" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ModeOfTracking">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="HomeVisit"/>
 *               &lt;enumeration value="HomeVisitPhoneCalls"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PatientContacted" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="PersonContacted" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Guardian"/>
 *               &lt;enumeration value="TreatmentSupporter"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReasonForAbsence" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="WasSick"/>
 *               &lt;enumeration value="NoTransportFare"/>
 *               &lt;enumeration value="TransferredOut"/>
 *               &lt;enumeration value="PatientForgotToAttendAppointment"/>
 *               &lt;enumeration value="FeltBetterAndStoppedTakingMedication"/>
 *               &lt;enumeration value="NotPermittedToLeaveWork"/>
 *               &lt;enumeration value="LostAppointmentCard"/>
 *               &lt;enumeration value="StillHadDrugs"/>
 *               &lt;enumeration value="HerbalTraditionalMedicine"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherReasonRorDefaulting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SolutionToAbsence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TBTrackingOutcome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="ActiveStatus"/>
 *               &lt;enumeration value="InactiveStatus"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBInterruptionTrackingType", propOrder = { "visitID", "visitDate", "trackingAttempts",
        "dateOfLastDrugIntake", "modeOfTracking", "patientContacted", "personContacted", "reasonForAbsence",
        "otherReasonRorDefaulting", "solutionToAbsence", "tbTrackingOutcome" })
public class TBInterruptionTrackingType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "TrackingAttempts")
	protected String trackingAttempts;
	
	@XmlElement(name = "DateOfLastDrugIntake")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateOfLastDrugIntake;
	
	@XmlElement(name = "ModeOfTracking", required = true)
	protected String modeOfTracking;
	
	@XmlElement(name = "PatientContacted")
	@XmlSchemaType(name = "string")
	protected YNCodeType patientContacted;
	
	@XmlElement(name = "PersonContacted")
	protected String personContacted;
	
	@XmlElement(name = "ReasonForAbsence")
	protected String reasonForAbsence;
	
	@XmlElement(name = "OtherReasonRorDefaulting")
	protected String otherReasonRorDefaulting;
	
	@XmlElement(name = "SolutionToAbsence")
	protected String solutionToAbsence;
	
	@XmlElement(name = "TBTrackingOutcome")
	protected String tbTrackingOutcome;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the trackingAttempts property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTrackingAttempts() {
		return trackingAttempts;
	}
	
	/**
	 * Sets the value of the trackingAttempts property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTrackingAttempts(String value) {
		this.trackingAttempts = value;
	}
	
	/**
	 * Gets the value of the dateOfLastDrugIntake property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateOfLastDrugIntake() {
		return dateOfLastDrugIntake;
	}
	
	/**
	 * Sets the value of the dateOfLastDrugIntake property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateOfLastDrugIntake(XMLGregorianCalendar value) {
		this.dateOfLastDrugIntake = value;
	}
	
	/**
	 * Gets the value of the modeOfTracking property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getModeOfTracking() {
		return modeOfTracking;
	}
	
	/**
	 * Sets the value of the modeOfTracking property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setModeOfTracking(String value) {
		this.modeOfTracking = value;
	}
	
	/**
	 * Gets the value of the patientContacted property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getPatientContacted() {
		return patientContacted;
	}
	
	/**
	 * Sets the value of the patientContacted property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setPatientContacted(YNCodeType value) {
		this.patientContacted = value;
	}
	
	/**
	 * Gets the value of the personContacted property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPersonContacted() {
		return personContacted;
	}
	
	/**
	 * Sets the value of the personContacted property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPersonContacted(String value) {
		this.personContacted = value;
	}
	
	/**
	 * Gets the value of the reasonForAbsence property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReasonForAbsence() {
		return reasonForAbsence;
	}
	
	/**
	 * Sets the value of the reasonForAbsence property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setReasonForAbsence(String value) {
		this.reasonForAbsence = value;
	}
	
	/**
	 * Gets the value of the otherReasonRorDefaulting property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOtherReasonRorDefaulting() {
		return otherReasonRorDefaulting;
	}
	
	/**
	 * Sets the value of the otherReasonRorDefaulting property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setOtherReasonRorDefaulting(String value) {
		this.otherReasonRorDefaulting = value;
	}
	
	/**
	 * Gets the value of the solutionToAbsence property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSolutionToAbsence() {
		return solutionToAbsence;
	}
	
	/**
	 * Sets the value of the solutionToAbsence property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSolutionToAbsence(String value) {
		this.solutionToAbsence = value;
	}
	
	/**
	 * Gets the value of the tbTrackingOutcome property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTBTrackingOutcome() {
		return tbTrackingOutcome;
	}
	
	/**
	 * Sets the value of the tbTrackingOutcome property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTBTrackingOutcome(String value) {
		this.tbTrackingOutcome = value;
	}
	
}
