//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.09.07 at 04:26:15 PM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TBScreeningType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBScreeningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{}StringType"/>
 *         &lt;element name="DateOfVisit" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TBRegistrationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentCough" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="WeightLoss" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="Fever" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="NightSweats" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="ContactWithTBPatient" type="{}YNCodeType" minOccurs="0"/>
 *         &lt;element name="TBScreeningScore" type="{}NumericType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBScreeningType", propOrder = { "visitID", "dateOfVisit", "tbRegistrationId", "currentCough", "weightLoss",
        "fever", "nightSweats", "contactWithTBPatient", "tbScreeningScore" })
public class TBScreeningType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "DateOfVisit", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateOfVisit;
	
	@XmlElement(name = "TBRegistrationId", required = true)
	protected String tbRegistrationId;
	
	@XmlElement(name = "CurrentCough")
	@XmlSchemaType(name = "string")
	protected YNCodeType currentCough;
	
	@XmlElement(name = "WeightLoss")
	@XmlSchemaType(name = "string")
	protected YNCodeType weightLoss;
	
	@XmlElement(name = "Fever")
	@XmlSchemaType(name = "string")
	protected YNCodeType fever;
	
	@XmlElement(name = "NightSweats")
	@XmlSchemaType(name = "string")
	protected YNCodeType nightSweats;
	
	@XmlElement(name = "ContactWithTBPatient")
	@XmlSchemaType(name = "string")
	protected YNCodeType contactWithTBPatient;
	
	@XmlElement(name = "TBScreeningScore")
	protected Integer tbScreeningScore;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the dateOfVisit property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getDateOfVisit() {
		return dateOfVisit;
	}
	
	/**
	 * Sets the value of the dateOfVisit property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setDateOfVisit(XMLGregorianCalendar value) {
		this.dateOfVisit = value;
	}
	
	/**
	 * Gets the value of the tbRegistrationId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTBRegistrationId() {
		return tbRegistrationId;
	}
	
	/**
	 * Sets the value of the tbRegistrationId property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTBRegistrationId(String value) {
		this.tbRegistrationId = value;
	}
	
	/**
	 * Gets the value of the currentCough property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getCurrentCough() {
		return currentCough;
	}
	
	/**
	 * Sets the value of the currentCough property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setCurrentCough(YNCodeType value) {
		this.currentCough = value;
	}
	
	/**
	 * Gets the value of the weightLoss property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getWeightLoss() {
		return weightLoss;
	}
	
	/**
	 * Sets the value of the weightLoss property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setWeightLoss(YNCodeType value) {
		this.weightLoss = value;
	}
	
	/**
	 * Gets the value of the fever property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getFever() {
		return fever;
	}
	
	/**
	 * Sets the value of the fever property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setFever(YNCodeType value) {
		this.fever = value;
	}
	
	/**
	 * Gets the value of the nightSweats property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getNightSweats() {
		return nightSweats;
	}
	
	/**
	 * Sets the value of the nightSweats property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setNightSweats(YNCodeType value) {
		this.nightSweats = value;
	}
	
	/**
	 * Gets the value of the contactWithTBPatient property.
	 * 
	 * @return possible object is {@link YNCodeType }
	 */
	public YNCodeType getContactWithTBPatient() {
		return contactWithTBPatient;
	}
	
	/**
	 * Sets the value of the contactWithTBPatient property.
	 * 
	 * @param value allowed object is {@link YNCodeType }
	 */
	public void setContactWithTBPatient(YNCodeType value) {
		this.contactWithTBPatient = value;
	}
	
	/**
	 * Gets the value of the tbScreeningScore property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public Integer getTBScreeningScore() {
		return tbScreeningScore;
	}
	
	/**
	 * Sets the value of the tbScreeningScore property.
	 * 
	 * @param value allowed object is {@link Integer }
	 */
	public void setTBScreeningScore(Integer value) {
		this.tbScreeningScore = value;
	}
	
}
