//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.11.23 at 09:34:14 AM WAT
//

package org.openmrs.module.nigeriaemr.model.ndr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TBTreatmentMonitoringType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBTreatmentMonitoringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TypeOfRegimen" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="SixMonths"/>
 *               &lt;enumeration value="TwelveMonths"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TreatmentAgeGroup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Pediatric"/>
 *               &lt;enumeration value="Adult"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PregnancyAndBreastfeedingStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Breastfeeding"/>
 *               &lt;enumeration value="NotPregnant"/>
 *               &lt;enumeration value="Pregnant"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntensivePhaseAntiTBDrugs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Rifampicin"/>
 *               &lt;enumeration value="Isoniazid"/>
 *               &lt;enumeration value="Pyrazinamide"/>
 *               &lt;enumeration value="Ethambutol"/>
 *               &lt;enumeration value="Rifabutin"/>
 *               &lt;enumeration value="RHZE"/>
 *               &lt;enumeration value="RHZ"/>
 *               &lt;enumeration value="RHE"/>
 *               &lt;enumeration value="EH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntensivePhaseAntiTBDrugStrength" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="1g"/>
 *               &lt;enumeration value="100mg"/>
 *               &lt;enumeration value="150mg"/>
 *               &lt;enumeration value="300mg"/>
 *               &lt;enumeration value="400mg"/>
 *               &lt;enumeration value="150mg/75mg"/>
 *               &lt;enumeration value="300mg/150mg"/>
 *               &lt;enumeration value="150mg/75mg/45mg"/>
 *               &lt;enumeration value="kit"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntensivePhaseDrugFrequency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="OD"/>
 *               &lt;enumeration value="BD"/>
 *               &lt;enumeration value="2BD"/>
 *               &lt;enumeration value="3BD"/>
 *               &lt;enumeration value="4BD"/>
 *               &lt;enumeration value="QDS"/>
 *               &lt;enumeration value="3cePerweek"/>
 *               &lt;enumeration value="Nocte"/>
 *               &lt;enumeration value="Others"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntensivePhaseTBDrugDuration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="TwoMonths"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IntensivePhaseQuantityOfMedicationPrescribed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ContinuityPhaseAntiTBDrugs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Rifampicin"/>
 *               &lt;enumeration value="Isoniazid"/>
 *               &lt;enumeration value="Pyrazinamide"/>
 *               &lt;enumeration value="Ethambutol"/>
 *               &lt;enumeration value="Rifabutin"/>
 *               &lt;enumeration value="RHZE"/>
 *               &lt;enumeration value="RHZ"/>
 *               &lt;enumeration value="RHE"/>
 *               &lt;enumeration value="EH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ContinuityPhaseAntiTBDrugStrength" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="1g"/>
 *               &lt;enumeration value="100mg"/>
 *               &lt;enumeration value="150mg"/>
 *               &lt;enumeration value="300mg"/>
 *               &lt;enumeration value="400mg"/>
 *               &lt;enumeration value="150mg/75mg"/>
 *               &lt;enumeration value="300mg/150mg"/>
 *               &lt;enumeration value="150mg/75mg/45mg"/>
 *               &lt;enumeration value="kit"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ContinuityPhaseDrugFrequency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="OD"/>
 *               &lt;enumeration value="BD"/>
 *               &lt;enumeration value="2BD"/>
 *               &lt;enumeration value="3BD"/>
 *               &lt;enumeration value="4BD"/>
 *               &lt;enumeration value="QDS"/>
 *               &lt;enumeration value="3cePerweek"/>
 *               &lt;enumeration value="Nocte"/>
 *               &lt;enumeration value="Others"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ContinuityPhaseTBDrugDuration" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="FourMonths"/>
 *               &lt;enumeration value="TenMonths"/>
 *               &lt;enumeration value="TwelveMonths"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ContinuityPhaseQuantityOfMedicationPrescribed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SelectOutcome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="Cured"/>
 *               &lt;enumeration value="TreatmentCompleted"/>
 *               &lt;enumeration value="TreatmentFailed"/>
 *               &lt;enumeration value="NotEvaluated"/>
 *               &lt;enumeration value="LostToFollowUp"/>
 *               &lt;enumeration value="Dead"/>
 *               &lt;enumeration value="RemovedFromRegister"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TBTreatmentOutcomeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DOTProviderType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="TreatmentSupporter"/>
 *               &lt;enumeration value="HealthCareWorker"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OutcomeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DOTProviderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBTreatmentMonitoringType", propOrder = { "visitID", "visitDate", "typeOfRegimen", "treatmentAgeGroup",
        "pregnancyAndBreastfeedingStatus", "intensivePhaseAntiTBDrugs", "intensivePhaseAntiTBDrugStrength",
        "intensivePhaseDrugFrequency", "intensivePhaseTBDrugDuration", "intensivePhaseQuantityOfMedicationPrescribed",
        "continuityPhaseAntiTBDrugs", "continuityPhaseAntiTBDrugStrength", "continuityPhaseDrugFrequency",
        "continuityPhaseTBDrugDuration", "continuityPhaseQuantityOfMedicationPrescribed", "selectOutcome",
        "tbTreatmentOutcomeDate", "dotProviderType", "outcomeDate", "dotProviderName" })
public class TBTreatmentMonitoringType {
	
	@XmlElement(name = "VisitID", required = true)
	protected String visitID;
	
	@XmlElement(name = "VisitDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar visitDate;
	
	@XmlElement(name = "TypeOfRegimen")
	protected String typeOfRegimen;
	
	@XmlElement(name = "TreatmentAgeGroup")
	protected String treatmentAgeGroup;
	
	@XmlElement(name = "PregnancyAndBreastfeedingStatus")
	protected String pregnancyAndBreastfeedingStatus;
	
	@XmlElement(name = "IntensivePhaseAntiTBDrugs")
	protected String intensivePhaseAntiTBDrugs;
	
	@XmlElement(name = "IntensivePhaseAntiTBDrugStrength")
	protected String intensivePhaseAntiTBDrugStrength;
	
	@XmlElement(name = "IntensivePhaseDrugFrequency")
	protected String intensivePhaseDrugFrequency;
	
	@XmlElement(name = "IntensivePhaseTBDrugDuration")
	protected String intensivePhaseTBDrugDuration;
	
	@XmlElement(name = "IntensivePhaseQuantityOfMedicationPrescribed")
	protected Integer intensivePhaseQuantityOfMedicationPrescribed;
	
	@XmlElement(name = "ContinuityPhaseAntiTBDrugs")
	protected String continuityPhaseAntiTBDrugs;
	
	@XmlElement(name = "ContinuityPhaseAntiTBDrugStrength")
	protected String continuityPhaseAntiTBDrugStrength;
	
	@XmlElement(name = "ContinuityPhaseDrugFrequency")
	protected String continuityPhaseDrugFrequency;
	
	@XmlElement(name = "ContinuityPhaseTBDrugDuration")
	protected String continuityPhaseTBDrugDuration;
	
	@XmlElement(name = "ContinuityPhaseQuantityOfMedicationPrescribed")
	protected Integer continuityPhaseQuantityOfMedicationPrescribed;
	
	@XmlElement(name = "SelectOutcome")
	protected String selectOutcome;
	
	@XmlElement(name = "TBTreatmentOutcomeDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar tbTreatmentOutcomeDate;
	
	@XmlElement(name = "DOTProviderType")
	protected String dotProviderType;
	
	@XmlElement(name = "OutcomeDate")
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar outcomeDate;
	
	@XmlElement(name = "DOTProviderName")
	protected String dotProviderName;
	
	/**
	 * Gets the value of the visitID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getVisitID() {
		return visitID;
	}
	
	/**
	 * Sets the value of the visitID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setVisitID(String value) {
		this.visitID = value;
	}
	
	/**
	 * Gets the value of the visitDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getVisitDate() {
		return visitDate;
	}
	
	/**
	 * Sets the value of the visitDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setVisitDate(XMLGregorianCalendar value) {
		this.visitDate = value;
	}
	
	/**
	 * Gets the value of the typeOfRegimen property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTypeOfRegimen() {
		return typeOfRegimen;
	}
	
	/**
	 * Sets the value of the typeOfRegimen property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTypeOfRegimen(String value) {
		this.typeOfRegimen = value;
	}
	
	/**
	 * Gets the value of the treatmentAgeGroup property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTreatmentAgeGroup() {
		return treatmentAgeGroup;
	}
	
	/**
	 * Sets the value of the treatmentAgeGroup property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setTreatmentAgeGroup(String value) {
		this.treatmentAgeGroup = value;
	}
	
	/**
	 * Gets the value of the pregnancyAndBreastfeedingStatus property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPregnancyAndBreastfeedingStatus() {
		return pregnancyAndBreastfeedingStatus;
	}
	
	/**
	 * Sets the value of the pregnancyAndBreastfeedingStatus property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setPregnancyAndBreastfeedingStatus(String value) {
		this.pregnancyAndBreastfeedingStatus = value;
	}
	
	/**
	 * Gets the value of the intensivePhaseAntiTBDrugs property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIntensivePhaseAntiTBDrugs() {
		return intensivePhaseAntiTBDrugs;
	}
	
	/**
	 * Sets the value of the intensivePhaseAntiTBDrugs property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setIntensivePhaseAntiTBDrugs(String value) {
		this.intensivePhaseAntiTBDrugs = value;
	}
	
	/**
	 * Gets the value of the intensivePhaseAntiTBDrugStrength property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIntensivePhaseAntiTBDrugStrength() {
		return intensivePhaseAntiTBDrugStrength;
	}
	
	/**
	 * Sets the value of the intensivePhaseAntiTBDrugStrength property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setIntensivePhaseAntiTBDrugStrength(String value) {
		this.intensivePhaseAntiTBDrugStrength = value;
	}
	
	/**
	 * Gets the value of the intensivePhaseDrugFrequency property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIntensivePhaseDrugFrequency() {
		return intensivePhaseDrugFrequency;
	}
	
	/**
	 * Sets the value of the intensivePhaseDrugFrequency property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setIntensivePhaseDrugFrequency(String value) {
		this.intensivePhaseDrugFrequency = value;
	}
	
	/**
	 * Gets the value of the intensivePhaseTBDrugDuration property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getIntensivePhaseTBDrugDuration() {
		return intensivePhaseTBDrugDuration;
	}
	
	/**
	 * Sets the value of the intensivePhaseTBDrugDuration property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setIntensivePhaseTBDrugDuration(String value) {
		this.intensivePhaseTBDrugDuration = value;
	}
	
	/**
	 * Gets the value of the intensivePhaseQuantityOfMedicationPrescribed property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public Integer getIntensivePhaseQuantityOfMedicationPrescribed() {
		return intensivePhaseQuantityOfMedicationPrescribed;
	}
	
	/**
	 * Sets the value of the intensivePhaseQuantityOfMedicationPrescribed property.
	 * 
	 * @param value allowed object is {@link Integer }
	 */
	public void setIntensivePhaseQuantityOfMedicationPrescribed(Integer value) {
		this.intensivePhaseQuantityOfMedicationPrescribed = value;
	}
	
	/**
	 * Gets the value of the continuityPhaseAntiTBDrugs property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getContinuityPhaseAntiTBDrugs() {
		return continuityPhaseAntiTBDrugs;
	}
	
	/**
	 * Sets the value of the continuityPhaseAntiTBDrugs property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setContinuityPhaseAntiTBDrugs(String value) {
		this.continuityPhaseAntiTBDrugs = value;
	}
	
	/**
	 * Gets the value of the continuityPhaseAntiTBDrugStrength property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getContinuityPhaseAntiTBDrugStrength() {
		return continuityPhaseAntiTBDrugStrength;
	}
	
	/**
	 * Sets the value of the continuityPhaseAntiTBDrugStrength property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setContinuityPhaseAntiTBDrugStrength(String value) {
		this.continuityPhaseAntiTBDrugStrength = value;
	}
	
	/**
	 * Gets the value of the continuityPhaseDrugFrequency property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getContinuityPhaseDrugFrequency() {
		return continuityPhaseDrugFrequency;
	}
	
	/**
	 * Sets the value of the continuityPhaseDrugFrequency property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setContinuityPhaseDrugFrequency(String value) {
		this.continuityPhaseDrugFrequency = value;
	}
	
	/**
	 * Gets the value of the continuityPhaseTBDrugDuration property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getContinuityPhaseTBDrugDuration() {
		return continuityPhaseTBDrugDuration;
	}
	
	/**
	 * Sets the value of the continuityPhaseTBDrugDuration property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setContinuityPhaseTBDrugDuration(String value) {
		this.continuityPhaseTBDrugDuration = value;
	}
	
	/**
	 * Gets the value of the continuityPhaseQuantityOfMedicationPrescribed property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public Integer getContinuityPhaseQuantityOfMedicationPrescribed() {
		return continuityPhaseQuantityOfMedicationPrescribed;
	}
	
	/**
	 * Sets the value of the continuityPhaseQuantityOfMedicationPrescribed property.
	 * 
	 * @param value allowed object is {@link Integer }
	 */
	public void setContinuityPhaseQuantityOfMedicationPrescribed(Integer value) {
		this.continuityPhaseQuantityOfMedicationPrescribed = value;
	}
	
	/**
	 * Gets the value of the selectOutcome property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSelectOutcome() {
		return selectOutcome;
	}
	
	/**
	 * Sets the value of the selectOutcome property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setSelectOutcome(String value) {
		this.selectOutcome = value;
	}
	
	/**
	 * Gets the value of the tbTreatmentOutcomeDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getTBTreatmentOutcomeDate() {
		return tbTreatmentOutcomeDate;
	}
	
	/**
	 * Sets the value of the tbTreatmentOutcomeDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setTBTreatmentOutcomeDate(XMLGregorianCalendar value) {
		this.tbTreatmentOutcomeDate = value;
	}
	
	/**
	 * Gets the value of the dotProviderType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDOTProviderType() {
		return dotProviderType;
	}
	
	/**
	 * Sets the value of the dotProviderType property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDOTProviderType(String value) {
		this.dotProviderType = value;
	}
	
	/**
	 * Gets the value of the outcomeDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getOutcomeDate() {
		return outcomeDate;
	}
	
	/**
	 * Sets the value of the outcomeDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setOutcomeDate(XMLGregorianCalendar value) {
		this.outcomeDate = value;
	}
	
	/**
	 * Gets the value of the dotProviderName property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDOTProviderName() {
		return dotProviderName;
	}
	
	/**
	 * Sets the value of the dotProviderName property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setDOTProviderName(String value) {
		this.dotProviderName = value;
	}
	
}
